# See https://pub.dev/packages/mono_repo
sdk:
- 2.14.0
- dev

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos .
# Need to wire up Google auth on CI before we can test this on...CI
#- unittest:
#  - test:
