{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud-platform": {
                    "description": "View and manage your data across Google Cloud Platform services"
                },
                "https://www.googleapis.com/auth/cloud-platform.read-only": {
                    "description": "View your data across Google Cloud Platform services"
                },
                "https://www.googleapis.com/auth/cloud.useraccounts": {
                    "description": "Manage your Google Cloud User Accounts"
                },
                "https://www.googleapis.com/auth/cloud.useraccounts.readonly": {
                    "description": "View your Google Cloud User Accounts"
                }
            }
        }
    },
    "basePath": "/clouduseraccounts/beta/projects/",
    "baseUrl": "https://www.googleapis.com/clouduseraccounts/beta/projects/",
    "batchPath": "batch",
    "canonicalName": "Cloud User Accounts",
    "description": "API for the Google Cloud User Accounts service.",
    "discoveryVersion": "v1",
    "documentationLink": "https://cloud.google.com/compute/docs/access/user-accounts/api/latest/",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/D519M8l2K6nc5aW0Rrh50t4ZQRE\"",
    "id": "clouduseraccounts:beta",
    "kind": "discovery#restDescription",
    "name": "clouduseraccounts",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "globalAccountsOperations": {
            "methods": {
                "delete": {
                    "description": "Deletes the specified operation resource.",
                    "httpMethod": "DELETE",
                    "id": "clouduseraccounts.globalAccountsOperations.delete",
                    "path": "{project}/global/operations/{operation}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "get": {
                    "description": "Retrieves the specified operation resource.",
                    "httpMethod": "GET",
                    "id": "clouduseraccounts.globalAccountsOperations.get",
                    "path": "{project}/global/operations/{operation}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieves the list of operation resources contained within the specified project.",
                    "httpMethod": "GET",
                    "id": "clouduseraccounts.globalAccountsOperations.list",
                    "path": "{project}/global/operations",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                }
            }
        },
        "groups": {
            "methods": {
                "addMember": {
                    "description": "Adds users to the specified group.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.groups.addMember",
                    "path": "{project}/global/groups/{groupName}/addMember",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "delete": {
                    "description": "Deletes the specified Group resource.",
                    "httpMethod": "DELETE",
                    "id": "clouduseraccounts.groups.delete",
                    "path": "{project}/global/groups/{groupName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "get": {
                    "description": "Returns the specified Group resource.",
                    "httpMethod": "GET",
                    "id": "clouduseraccounts.groups.get",
                    "path": "{project}/global/groups/{groupName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates a Group resource in the specified project using the data included in the request.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.groups.insert",
                    "path": "{project}/global/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "list": {
                    "description": "Retrieves the list of groups contained within the specified project.",
                    "httpMethod": "GET",
                    "id": "clouduseraccounts.groups.list",
                    "path": "{project}/global/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                },
                "removeMember": {
                    "description": "Removes users from the specified group.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.groups.removeMember",
                    "path": "{project}/global/groups/{groupName}/removeMember",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                }
            }
        },
        "linux": {
            "methods": {
                "getAuthorizedKeysView": {
                    "description": "Returns a list of authorized public keys for a specific user account.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.linux.getAuthorizedKeysView",
                    "path": "{project}/zones/{zone}/authorizedKeysView/{user}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                },
                "getLinuxAccountViews": {
                    "description": "Retrieves a list of user accounts for an instance within a specific project.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.linux.getLinuxAccountViews",
                    "path": "{project}/zones/{zone}/linuxAccountViews",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                }
            }
        },
        "users": {
            "methods": {
                "addPublicKey": {
                    "description": "Adds a public key to the specified User resource with the data included in the request.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.users.addPublicKey",
                    "path": "{project}/global/users/{user}/addPublicKey",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "delete": {
                    "description": "Deletes the specified User resource.",
                    "httpMethod": "DELETE",
                    "id": "clouduseraccounts.users.delete",
                    "path": "{project}/global/users/{user}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "get": {
                    "description": "Returns the specified User resource.",
                    "httpMethod": "GET",
                    "id": "clouduseraccounts.users.get",
                    "path": "{project}/global/users/{user}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates a User resource in the specified project using the data included in the request.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.users.insert",
                    "path": "{project}/global/users",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                },
                "list": {
                    "description": "Retrieves a list of users contained within the specified project.",
                    "httpMethod": "GET",
                    "id": "clouduseraccounts.users.list",
                    "path": "{project}/global/users",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/cloud.useraccounts",
                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
                    ]
                },
                "removePublicKey": {
                    "description": "Removes the specified public key from the user.",
                    "httpMethod": "POST",
                    "id": "clouduseraccounts.users.removePublicKey",
                    "path": "{project}/global/users/{user}/removePublicKey",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud.useraccounts"
                    ]
                }
            }
        }
    },
    "revision": "20150924",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "clouduseraccounts/beta/projects/",
    "title": "Cloud User Accounts API",
    "version": "beta"
}