{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/bigquery": {
                    "description": "View and manage your data in Google BigQuery"
                },
                "https://www.googleapis.com/auth/devstorage.read_write": {
                    "description": "Manage your data in Google Cloud Storage"
                },
                "https://www.googleapis.com/auth/genomics": {
                    "description": "View and manage Genomics data"
                },
                "https://www.googleapis.com/auth/genomics.readonly": {
                    "description": "View Genomics data"
                }
            }
        }
    },
    "basePath": "/genomics/v1beta2/",
    "baseUrl": "https://www.googleapis.com/genomics/v1beta2/",
    "batchPath": "batch",
    "description": "Provides access to Genomics data.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/genomics/v1beta2/reference",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/GQ8G6h803bhAihV7tJKOVvj6RSc\"",
    "id": "genomics:v1beta2",
    "kind": "discovery#restDescription",
    "name": "genomics",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "callsets": {
            "methods": {
                "create": {
                    "description": "Creates a new call set.",
                    "httpMethod": "POST",
                    "id": "genomics.callsets.create",
                    "path": "callsets",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a call set.",
                    "httpMethod": "DELETE",
                    "id": "genomics.callsets.delete",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a call set by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.callsets.get",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a call set. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.callsets.patch",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Gets a list of call sets matching the criteria.\n\nImplements GlobalAllianceApi.searchCallSets.",
                    "httpMethod": "POST",
                    "id": "genomics.callsets.search",
                    "path": "callsets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a call set.",
                    "httpMethod": "PUT",
                    "id": "genomics.callsets.update",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        },
        "datasets": {
            "methods": {
                "create": {
                    "description": "Creates a new dataset.",
                    "httpMethod": "POST",
                    "id": "genomics.datasets.create",
                    "path": "datasets",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a dataset.",
                    "httpMethod": "DELETE",
                    "id": "genomics.datasets.delete",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a dataset by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.datasets.get",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "list": {
                    "description": "Lists all datasets.",
                    "httpMethod": "GET",
                    "id": "genomics.datasets.list",
                    "path": "datasets",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a dataset. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.datasets.patch",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "undelete": {
                    "description": "Undeletes a dataset by restoring a dataset which was deleted via this API. This operation is only possible for a week after the deletion occurred.",
                    "httpMethod": "POST",
                    "id": "genomics.datasets.undelete",
                    "path": "datasets/{datasetId}/undelete",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "update": {
                    "description": "Updates a dataset.",
                    "httpMethod": "PUT",
                    "id": "genomics.datasets.update",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        },
        "experimental": {
            "resources": {
                "jobs": {
                    "methods": {
                        "create": {
                            "description": "Creates and asynchronously runs an ad-hoc job. This is an experimental call and may be removed or changed at any time.",
                            "httpMethod": "POST",
                            "id": "genomics.experimental.jobs.create",
                            "path": "experimental/jobs/create",
                            "scopes": [
                                "https://www.googleapis.com/auth/devstorage.read_write",
                                "https://www.googleapis.com/auth/genomics"
                            ]
                        }
                    }
                }
            }
        },
        "jobs": {
            "methods": {
                "cancel": {
                    "description": "Cancels a job by ID. Note that it is possible for partial results to be generated and stored for cancelled jobs.",
                    "httpMethod": "POST",
                    "id": "genomics.jobs.cancel",
                    "path": "jobs/{jobId}/cancel",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a job by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.jobs.get",
                    "path": "jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "search": {
                    "description": "Gets a list of jobs matching the criteria.",
                    "httpMethod": "POST",
                    "id": "genomics.jobs.search",
                    "path": "jobs/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                }
            }
        },
        "readgroupsets": {
            "methods": {
                "align": {
                    "description": "Aligns read data from existing read group sets or files from Google Cloud Storage. See the  alignment and variant calling documentation for more details.",
                    "httpMethod": "POST",
                    "id": "genomics.readgroupsets.align",
                    "path": "readgroupsets/align",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "call": {
                    "description": "Calls variants on read data from existing read group sets or files from Google Cloud Storage. See the  alignment and variant calling documentation for more details.",
                    "httpMethod": "POST",
                    "id": "genomics.readgroupsets.call",
                    "path": "readgroupsets/call",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a read group set.",
                    "httpMethod": "DELETE",
                    "id": "genomics.readgroupsets.delete",
                    "path": "readgroupsets/{readGroupSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "export": {
                    "description": "Exports read group sets to a BAM file in Google Cloud Storage.\n\nNote that currently there may be some differences between exported BAM files and the original BAM file at the time of import. In particular, comments in the input file header will not be preserved, some custom tags will be converted to strings, and original reference sequence order is not necessarily preserved.",
                    "httpMethod": "POST",
                    "id": "genomics.readgroupsets.export",
                    "path": "readgroupsets/export",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a read group set by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.readgroupsets.get",
                    "path": "readgroupsets/{readGroupSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "import": {
                    "description": "Creates read group sets by asynchronously importing the provided information.\n\nNote that currently comments in the input file header are not imported and some custom tags will be converted to strings, rather than preserving tag types. The caller must have WRITE permissions to the dataset.",
                    "httpMethod": "POST",
                    "id": "genomics.readgroupsets.import",
                    "path": "readgroupsets/import",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "patch": {
                    "description": "Updates a read group set. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.readgroupsets.patch",
                    "path": "readgroupsets/{readGroupSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Searches for read group sets matching the criteria.\n\nImplements GlobalAllianceApi.searchReadGroupSets.",
                    "httpMethod": "POST",
                    "id": "genomics.readgroupsets.search",
                    "path": "readgroupsets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a read group set.",
                    "httpMethod": "PUT",
                    "id": "genomics.readgroupsets.update",
                    "path": "readgroupsets/{readGroupSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            },
            "resources": {
                "coveragebuckets": {
                    "methods": {
                        "list": {
                            "description": "Lists fixed width coverage buckets for a read group set, each of which correspond to a range of a reference sequence. Each bucket summarizes coverage information across its corresponding genomic range.\n\nCoverage is defined as the number of reads which are aligned to a given base in the reference sequence. Coverage buckets are available at several precomputed bucket widths, enabling retrieval of various coverage 'zoom levels'. The caller must have REA[...]",
                            "httpMethod": "GET",
                            "id": "genomics.readgroupsets.coveragebuckets.list",
                            "path": "readgroupsets/{readGroupSetId}/coveragebuckets",
                            "scopes": [
                                "https://www.googleapis.com/auth/genomics",
                                "https://www.googleapis.com/auth/genomics.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "reads": {
            "methods": {
                "search": {
                    "description": "Gets a list of reads for one or more read group sets. Reads search operates over a genomic coordinate space of reference sequence & position defined over the reference sequences to which the requested read group sets are aligned.\n\nIf a target positional range is specified, search returns all reads whose alignment to the reference genome overlap the range. A query which specifies only read group set IDs yields all reads in those read group sets, including unm[...]",
                    "httpMethod": "POST",
                    "id": "genomics.reads.search",
                    "path": "reads/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                }
            }
        },
        "references": {
            "methods": {
                "get": {
                    "description": "Gets a reference.\n\nImplements GlobalAllianceApi.getReference.",
                    "httpMethod": "GET",
                    "id": "genomics.references.get",
                    "path": "references/{referenceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "search": {
                    "description": "Searches for references which match the given criteria.\n\nImplements GlobalAllianceApi.searchReferences.",
                    "httpMethod": "POST",
                    "id": "genomics.references.search",
                    "path": "references/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                }
            },
            "resources": {
                "bases": {
                    "methods": {
                        "list": {
                            "description": "Lists the bases in a reference, optionally restricted to a range.\n\nImplements GlobalAllianceApi.getReferenceBases.",
                            "httpMethod": "GET",
                            "id": "genomics.references.bases.list",
                            "path": "references/{referenceId}/bases",
                            "scopes": [
                                "https://www.googleapis.com/auth/genomics",
                                "https://www.googleapis.com/auth/genomics.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "referencesets": {
            "methods": {
                "get": {
                    "description": "Gets a reference set.\n\nImplements GlobalAllianceApi.getReferenceSet.",
                    "httpMethod": "GET",
                    "id": "genomics.referencesets.get",
                    "path": "referencesets/{referenceSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "search": {
                    "description": "Searches for reference sets which match the given criteria.\n\nImplements GlobalAllianceApi.searchReferenceSets.",
                    "httpMethod": "POST",
                    "id": "genomics.referencesets.search",
                    "path": "referencesets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                }
            }
        },
        "variants": {
            "methods": {
                "create": {
                    "description": "Creates a new variant.",
                    "httpMethod": "POST",
                    "id": "genomics.variants.create",
                    "path": "variants",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a variant.",
                    "httpMethod": "DELETE",
                    "id": "genomics.variants.delete",
                    "path": "variants/{variantId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a variant by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.variants.get",
                    "path": "variants/{variantId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "search": {
                    "description": "Gets a list of variants matching the criteria.\n\nImplements GlobalAllianceApi.searchVariants.",
                    "httpMethod": "POST",
                    "id": "genomics.variants.search",
                    "path": "variants/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a variant's names and info fields. All other modifications are silently ignored. Returns the modified variant without its calls.",
                    "httpMethod": "PUT",
                    "id": "genomics.variants.update",
                    "path": "variants/{variantId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        },
        "variantsets": {
            "methods": {
                "delete": {
                    "description": "Deletes the contents of a variant set. The variant set object is not deleted.",
                    "httpMethod": "DELETE",
                    "id": "genomics.variantsets.delete",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "export": {
                    "description": "Exports variant set data to an external destination.",
                    "httpMethod": "POST",
                    "id": "genomics.variantsets.export",
                    "path": "variantsets/{variantSetId}/export",
                    "scopes": [
                        "https://www.googleapis.com/auth/bigquery",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a variant set by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.variantsets.get",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "importVariants": {
                    "description": "Creates variant data by asynchronously importing the provided information.\n\nThe variants for import will be merged with any existing data and each other according to the behavior of mergeVariants. In particular, this means for merged VCF variants that have conflicting INFO fields, some data will be arbitrarily discarded. As a special case, for single-sample VCF files, QUAL and FILTER fields will be moved to the call level; these are sometimes interpreted in [...]",
                    "httpMethod": "POST",
                    "id": "genomics.variantsets.importVariants",
                    "path": "variantsets/{variantSetId}/importVariants",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "mergeVariants": {
                    "description": "Merges the given variants with existing variants. Each variant will be merged with an existing variant that matches its reference sequence, start, end, reference bases, and alternative bases. If no such variant exists, a new one will be created.\n\nWhen variants are merged, the call information from the new variant is added to the existing variant, and other fields (such as key/value pairs) are discarded.",
                    "httpMethod": "POST",
                    "id": "genomics.variantsets.mergeVariants",
                    "path": "variantsets/{variantSetId}/mergeVariants"
                },
                "patch": {
                    "description": "Updates a variant set's metadata. All other modifications are silently ignored. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.variantsets.patch",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Returns a list of all variant sets matching search criteria.\n\nImplements GlobalAllianceApi.searchVariantSets.",
                    "httpMethod": "POST",
                    "id": "genomics.variantsets.search",
                    "path": "variantsets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a variant set's metadata. All other modifications are silently ignored.",
                    "httpMethod": "PUT",
                    "id": "genomics.variantsets.update",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        }
    },
    "revision": "20150106",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "genomics/v1beta2/",
    "title": "Genomics API",
    "version": "v1beta2"
}