{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/bigquery": {
                    "description": "View and manage your data in Google BigQuery"
                },
                "https://www.googleapis.com/auth/devstorage.read_write": {
                    "description": "Manage your data in Google Cloud Storage"
                },
                "https://www.googleapis.com/auth/genomics": {
                    "description": "View and manage Genomics data"
                },
                "https://www.googleapis.com/auth/genomics.readonly": {
                    "description": "View Genomics data"
                }
            }
        }
    },
    "basePath": "/genomics/v1beta/",
    "baseUrl": "https://www.googleapis.com/genomics/v1beta/",
    "batchPath": "batch",
    "description": "Provides access to Genomics data.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/genomics/v1beta/reference",
    "etag": "\"l66ggWbucbkBw9Lpos72oziyefE/QFkFkv2LMi0ob1p4dyYfQYJIVYc\"",
    "id": "genomics:v1beta",
    "kind": "discovery#restDescription",
    "name": "genomics",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "beacons": {
            "methods": {
                "get": {
                    "description": "This is an experimental API that provides a Global Alliance for Genomics and Health Beacon. It may change at any time.",
                    "httpMethod": "GET",
                    "id": "genomics.beacons.get",
                    "path": "beacons/{variantSetId}"
                }
            }
        },
        "callsets": {
            "methods": {
                "create": {
                    "description": "Creates a new call set.",
                    "httpMethod": "POST",
                    "id": "genomics.callsets.create",
                    "path": "callsets",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a call set.",
                    "httpMethod": "DELETE",
                    "id": "genomics.callsets.delete",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a call set by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.callsets.get",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a call set. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.callsets.patch",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Gets a list of call sets matching the criteria.",
                    "httpMethod": "POST",
                    "id": "genomics.callsets.search",
                    "path": "callsets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a call set.",
                    "httpMethod": "PUT",
                    "id": "genomics.callsets.update",
                    "path": "callsets/{callSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        },
        "datasets": {
            "methods": {
                "create": {
                    "description": "Creates a new dataset.",
                    "httpMethod": "POST",
                    "id": "genomics.datasets.create",
                    "path": "datasets",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a dataset.",
                    "httpMethod": "DELETE",
                    "id": "genomics.datasets.delete",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a dataset by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.datasets.get",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "list": {
                    "description": "Lists all datasets.",
                    "httpMethod": "GET",
                    "id": "genomics.datasets.list",
                    "path": "datasets",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a dataset. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.datasets.patch",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "undelete": {
                    "description": "Undeletes a dataset by restoring a dataset which was deleted via this API. This operation is only possible for a week after the deletion occurred.",
                    "httpMethod": "POST",
                    "id": "genomics.datasets.undelete",
                    "path": "datasets/{datasetId}/undelete",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "update": {
                    "description": "Updates a dataset.",
                    "httpMethod": "PUT",
                    "id": "genomics.datasets.update",
                    "path": "datasets/{datasetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        },
        "experimental": {
            "resources": {
                "jobs": {
                    "methods": {
                        "create": {
                            "description": "Creates and asynchronously runs an ad-hoc job. This is an experimental call and may be removed or changed at any time.",
                            "httpMethod": "POST",
                            "id": "genomics.experimental.jobs.create",
                            "path": "experimental/jobs/create",
                            "scopes": [
                                "https://www.googleapis.com/auth/devstorage.read_write",
                                "https://www.googleapis.com/auth/genomics"
                            ]
                        }
                    }
                }
            }
        },
        "jobs": {
            "methods": {
                "cancel": {
                    "description": "Cancels a job by ID. Note that it is possible for partial results to be generated and stored for cancelled jobs.",
                    "httpMethod": "POST",
                    "id": "genomics.jobs.cancel",
                    "path": "jobs/{jobId}/cancel",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a job by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.jobs.get",
                    "path": "jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "search": {
                    "description": "Gets a list of jobs matching the criteria.",
                    "httpMethod": "POST",
                    "id": "genomics.jobs.search",
                    "path": "jobs/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                }
            }
        },
        "reads": {
            "methods": {
                "search": {
                    "description": "Gets a list of reads for one or more readsets. Reads search operates over a genomic coordinate space of reference sequence & position defined over the reference sequences to which the requested readsets are aligned. If a target positional range is specified, search returns all reads whose alignment to the reference genome overlap the range. A query which specifies only readset IDs yields all reads in those readsets, including unmapped reads. All reads returned[...]",
                    "httpMethod": "POST",
                    "id": "genomics.reads.search",
                    "path": "reads/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                }
            }
        },
        "readsets": {
            "methods": {
                "delete": {
                    "description": "Deletes a readset.",
                    "httpMethod": "DELETE",
                    "id": "genomics.readsets.delete",
                    "path": "readsets/{readsetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "export": {
                    "description": "Exports readsets to a BAM file in Google Cloud Storage. Note that currently there may be some differences between exported BAM files and the original BAM file at the time of import. In particular, comments in the input file header will not be preserved, and some custom tags will be converted to strings.",
                    "httpMethod": "POST",
                    "id": "genomics.readsets.export",
                    "path": "readsets/export",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a readset by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.readsets.get",
                    "path": "readsets/{readsetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "import": {
                    "description": "Creates readsets by asynchronously importing the provided information. Note that currently comments in the input file header are not imported and some custom tags will be converted to strings, rather than preserving tag types. The caller must have WRITE permissions to the dataset.",
                    "httpMethod": "POST",
                    "id": "genomics.readsets.import",
                    "path": "readsets/import",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "patch": {
                    "description": "Updates a readset. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.readsets.patch",
                    "path": "readsets/{readsetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Gets a list of readsets matching the criteria.",
                    "httpMethod": "POST",
                    "id": "genomics.readsets.search",
                    "path": "readsets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a readset.",
                    "httpMethod": "PUT",
                    "id": "genomics.readsets.update",
                    "path": "readsets/{readsetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            },
            "resources": {
                "coveragebuckets": {
                    "methods": {
                        "list": {
                            "description": "Lists fixed width coverage buckets for a readset, each of which correspond to a range of a reference sequence. Each bucket summarizes coverage information across its corresponding genomic range. Coverage is defined as the number of reads which are aligned to a given base in the reference sequence. Coverage buckets are available at various bucket widths, enabling various coverage \"zoom levels\". The caller must have READ permissions for the target read[...]",
                            "httpMethod": "GET",
                            "id": "genomics.readsets.coveragebuckets.list",
                            "path": "readsets/{readsetId}/coveragebuckets",
                            "scopes": [
                                "https://www.googleapis.com/auth/genomics",
                                "https://www.googleapis.com/auth/genomics.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "variants": {
            "methods": {
                "create": {
                    "description": "Creates a new variant.",
                    "httpMethod": "POST",
                    "id": "genomics.variants.create",
                    "path": "variants",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "delete": {
                    "description": "Deletes a variant.",
                    "httpMethod": "DELETE",
                    "id": "genomics.variants.delete",
                    "path": "variants/{variantId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "export": {
                    "description": "Exports variant data to an external destination.",
                    "httpMethod": "POST",
                    "id": "genomics.variants.export",
                    "path": "variants/export",
                    "scopes": [
                        "https://www.googleapis.com/auth/bigquery",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a variant by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.variants.get",
                    "path": "variants/{variantId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "import": {
                    "description": "Creates variant data by asynchronously importing the provided information. The variants for import will be merged with any existing data and each other according to the behavior of mergeVariants. In particular, this means for merged VCF variants that have conflicting INFO fields, some data will be arbitrarily discarded. As a special case, for single-sample VCF files, QUAL and FILTER fields will be moved to the call level; these are sometimes interpreted in a c[...]",
                    "httpMethod": "POST",
                    "id": "genomics.variants.import",
                    "path": "variants/import",
                    "scopes": [
                        "https://www.googleapis.com/auth/devstorage.read_write",
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Gets a list of variants matching the criteria.",
                    "httpMethod": "POST",
                    "id": "genomics.variants.search",
                    "path": "variants/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a variant's names and info fields. All other modifications are silently ignored. Returns the modified variant without its calls.",
                    "httpMethod": "PUT",
                    "id": "genomics.variants.update",
                    "path": "variants/{variantId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        },
        "variantsets": {
            "methods": {
                "delete": {
                    "description": "Deletes the contents of a variant set. The variant set object is not deleted.",
                    "httpMethod": "DELETE",
                    "id": "genomics.variantsets.delete",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "get": {
                    "description": "Gets a variant set by ID.",
                    "httpMethod": "GET",
                    "id": "genomics.variantsets.get",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "mergeVariants": {
                    "description": "Merges the given variants with existing variants. Each variant will be merged with an existing variant that matches its reference sequence, start, end, reference bases, and alternative bases. If no such variant exists, a new one will be created.\n\nWhen variants are merged, the call information from the new variant is added to the existing variant, and other fields (such as key/value pairs) are discarded.",
                    "httpMethod": "POST",
                    "id": "genomics.variantsets.mergeVariants",
                    "path": "variantsets/{variantSetId}/mergeVariants"
                },
                "patch": {
                    "description": "Updates a variant set's metadata. All other modifications are silently ignored. Returns the modified variant set. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "genomics.variantsets.patch",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                },
                "search": {
                    "description": "Returns a list of all variant sets matching search criteria.",
                    "httpMethod": "POST",
                    "id": "genomics.variantsets.search",
                    "path": "variantsets/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics",
                        "https://www.googleapis.com/auth/genomics.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a variant set's metadata. All other modifications are silently ignored. Returns the modified variant set.",
                    "httpMethod": "PUT",
                    "id": "genomics.variantsets.update",
                    "path": "variantsets/{variantSetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/genomics"
                    ]
                }
            }
        }
    },
    "revision": "20141015",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "genomics/v1beta/",
    "title": "Genomics API",
    "version": "v1beta"
}