{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud-platform": {
                    "description": "View and manage your data across Google Cloud Platform services"
                },
                "https://www.googleapis.com/auth/replicapool": {
                    "description": "View and manage replica pools"
                },
                "https://www.googleapis.com/auth/replicapool.readonly": {
                    "description": "View replica pools"
                }
            }
        }
    },
    "basePath": "/replicapoolupdater/v1beta1/projects/",
    "baseUrl": "https://www.googleapis.com/replicapoolupdater/v1beta1/projects/",
    "batchPath": "batch",
    "description": "The Google Compute Engine Instance Group Updater API provides services for updating groups of Compute Engine Instances.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/compute/docs/instance-groups/manager/v1beta2",
    "etag": "\"l66ggWbucbkBw9Lpos72oziyefE/MkEFbbfro6Rau0xbZXwz9DhAfqM\"",
    "id": "replicapoolupdater:v1beta1",
    "kind": "discovery#restDescription",
    "labels": [
        "limited_availability"
    ],
    "name": "replicapoolupdater",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "updates": {
            "methods": {
                "cancel": {
                    "description": "Called on the particular Update endpoint. Cancels the update in state PAUSED. No-op if invoked in state CANCELLED.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.updates.cancel",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/cancel",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "get": {
                    "description": "Called on the particular Update endpoint. Returns the Update resource.",
                    "httpMethod": "GET",
                    "id": "replicapoolupdater.updates.get",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ]
                },
                "insert": {
                    "description": "Called on the collection endpoint. Inserts the new Update resource and starts the update.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.updates.insert",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "list": {
                    "description": "Called on the collection endpoint. Lists updates for a given instance group, in reverse chronological order. Pagination is supported, see ListRequestHeader.",
                    "httpMethod": "GET",
                    "id": "replicapoolupdater.updates.list",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ]
                },
                "pause": {
                    "description": "Called on the particular Update endpoint. Pauses the update in state from { ROLLING_FORWARD, ROLLING_BACK, PAUSED }. No-op if invoked in state PAUSED.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.updates.pause",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/pause",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "rollback": {
                    "description": "Called on the particular Update endpoint. Rolls back the update in state from { ROLLING_FORWARD, ROLLING_BACK, PAUSED }. No-op if invoked in state ROLLED_BACK.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.updates.rollback",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/rollback",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "rollforward": {
                    "description": "Called on the particular Update endpoint. Rolls forward the update in state from { ROLLING_FORWARD, ROLLING_BACK, PAUSED }. No-op if invoked in state ROLLED_OUT.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.updates.rollforward",
                    "path": "{project}/zones/{zone}/instanceGroupManagers/{instanceGroupManager}/updates/{update}/rollforward",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                }
            }
        }
    },
    "revision": "20141105",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "replicapoolupdater/v1beta1/projects/",
    "title": "Google Compute Engine Instance Group Updater API",
    "version": "v1beta1"
}