{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/cloud-platform": {
                    "description": "View and manage your data across Google Cloud Platform services"
                },
                "https://www.googleapis.com/auth/replicapool": {
                    "description": "View and manage replica pools"
                },
                "https://www.googleapis.com/auth/replicapool.readonly": {
                    "description": "View replica pools"
                }
            }
        }
    },
    "basePath": "/replicapoolupdater/v1beta1/projects/",
    "baseUrl": "https://www.googleapis.com/replicapoolupdater/v1beta1/projects/",
    "batchPath": "batch",
    "description": "The Google Compute Engine Instance Group Updater API provides services for updating groups of Compute Engine Instances.",
    "discoveryVersion": "v1",
    "documentationLink": "https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/AT-fnbTxTHlPDlbWlx4KZrEt53M\"",
    "id": "replicapoolupdater:v1beta1",
    "kind": "discovery#restDescription",
    "labels": [
        "limited_availability"
    ],
    "name": "replicapoolupdater",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "rollingUpdates": {
            "methods": {
                "cancel": {
                    "description": "Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.rollingUpdates.cancel",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/cancel",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "get": {
                    "description": "Returns information about an update.",
                    "httpMethod": "GET",
                    "id": "replicapoolupdater.rollingUpdates.get",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ]
                },
                "insert": {
                    "description": "Inserts and starts a new update.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.rollingUpdates.insert",
                    "path": "{project}/zones/{zone}/rollingUpdates",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "list": {
                    "description": "Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.",
                    "httpMethod": "GET",
                    "id": "replicapoolupdater.rollingUpdates.list",
                    "path": "{project}/zones/{zone}/rollingUpdates",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ]
                },
                "listInstanceUpdates": {
                    "description": "Lists the current status for each instance within a given update.",
                    "httpMethod": "GET",
                    "id": "replicapoolupdater.rollingUpdates.listInstanceUpdates",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/instanceUpdates",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ]
                },
                "pause": {
                    "description": "Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.rollingUpdates.pause",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/pause",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "resume": {
                    "description": "Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.rollingUpdates.resume",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/resume",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                },
                "rollback": {
                    "description": "Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.",
                    "httpMethod": "POST",
                    "id": "replicapoolupdater.rollingUpdates.rollback",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/rollback",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ]
                }
            }
        }
    },
    "revision": "20141227",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "replicapoolupdater/v1beta1/projects/",
    "title": "Google Compute Engine Instance Group Updater API",
    "version": "v1beta1"
}