{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/admin.directory.device.chromeos": {
                    "description": "View and manage your Chrome OS devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly": {
                    "description": "View your Chrome OS devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.device.mobile": {
                    "description": "View and manage your mobile devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.device.mobile.action": {
                    "description": "Manage your mobile devices by performing administrative tasks"
                },
                "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly": {
                    "description": "View your mobile devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.group": {
                    "description": "View and manage the provisioning of groups on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.group.member": {
                    "description": "View and manage group subscriptions on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.group.member.readonly": {
                    "description": "View group subscriptions on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.group.readonly": {
                    "description": "View groups on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.notifications": {
                    "description": "View and manage notifications received on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.orgunit": {
                    "description": "View and manage organization units on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.orgunit.readonly": {
                    "description": "View organization units on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user": {
                    "description": "View and manage the provisioning of users on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user.alias": {
                    "description": "View and manage user aliases on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly": {
                    "description": "View user aliases on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user.readonly": {
                    "description": "View users on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user.security": {
                    "description": "Manage data access permissions for users on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.userschema": {
                    "description": "View and manage the provisioning of user schemas on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.userschema.readonly": {
                    "description": "View user schemas on your domain"
                }
            }
        }
    },
    "basePath": "/admin/directory/v1/",
    "baseUrl": "https://www.googleapis.com/admin/directory/v1/",
    "batchPath": "batch",
    "canonicalName": "directory",
    "description": "The Admin SDK Directory API lets you view and manage enterprise resources such as users and groups, administrative notifications, security features, and more.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/admin-sdk/directory/",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/FINMPppbAsSW7hhRV2k9bEsVkrk\"",
    "id": "admin:directory_v1",
    "kind": "discovery#restDescription",
    "name": "admin",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "packagePath": "admin",
    "protocol": "rest",
    "resources": {
        "asps": {
            "methods": {
                "delete": {
                    "description": "Delete an ASP issued by a user.",
                    "httpMethod": "DELETE",
                    "id": "directory.asps.delete",
                    "path": "users/{userKey}/asps/{codeId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "get": {
                    "description": "Get information about an ASP issued by a user.",
                    "httpMethod": "GET",
                    "id": "directory.asps.get",
                    "path": "users/{userKey}/asps/{codeId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "list": {
                    "description": "List the ASPs issued by a user.",
                    "httpMethod": "GET",
                    "id": "directory.asps.list",
                    "path": "users/{userKey}/asps",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        },
        "channels": {
            "methods": {
                "stop": {
                    "description": "Stop watching resources through this channel",
                    "httpMethod": "POST",
                    "id": "admin.channels.stop",
                    "path": "/admin/directory_v1/channels/stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.alias",
                        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly"
                    ]
                }
            }
        },
        "chromeosdevices": {
            "methods": {
                "get": {
                    "description": "Retrieve Chrome OS Device",
                    "httpMethod": "GET",
                    "id": "directory.chromeosdevices.get",
                    "path": "customer/{customerId}/devices/chromeos/{deviceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos",
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieve all Chrome OS Devices of a customer (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.chromeosdevices.list",
                    "path": "customer/{customerId}/devices/chromeos",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos",
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
                    ]
                },
                "patch": {
                    "description": "Update Chrome OS Device. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.chromeosdevices.patch",
                    "path": "customer/{customerId}/devices/chromeos/{deviceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                    ]
                },
                "update": {
                    "description": "Update Chrome OS Device",
                    "httpMethod": "PUT",
                    "id": "directory.chromeosdevices.update",
                    "path": "customer/{customerId}/devices/chromeos/{deviceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                    ]
                }
            }
        },
        "groups": {
            "methods": {
                "delete": {
                    "description": "Delete Group",
                    "httpMethod": "DELETE",
                    "id": "directory.groups.delete",
                    "path": "groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                },
                "get": {
                    "description": "Retrieve Group",
                    "httpMethod": "GET",
                    "id": "directory.groups.get",
                    "path": "groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "insert": {
                    "description": "Create Group",
                    "httpMethod": "POST",
                    "id": "directory.groups.insert",
                    "path": "groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                },
                "list": {
                    "description": "Retrieve all groups in a domain (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.groups.list",
                    "path": "groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "patch": {
                    "description": "Update Group. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.groups.patch",
                    "path": "groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                },
                "update": {
                    "description": "Update Group",
                    "httpMethod": "PUT",
                    "id": "directory.groups.update",
                    "path": "groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                }
            },
            "resources": {
                "aliases": {
                    "methods": {
                        "delete": {
                            "description": "Remove a alias for the group",
                            "httpMethod": "DELETE",
                            "id": "directory.groups.aliases.delete",
                            "path": "groups/{groupKey}/aliases/{alias}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.group"
                            ]
                        },
                        "insert": {
                            "description": "Add a alias for the group",
                            "httpMethod": "POST",
                            "id": "directory.groups.aliases.insert",
                            "path": "groups/{groupKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.group"
                            ]
                        },
                        "list": {
                            "description": "List all aliases for a group",
                            "httpMethod": "GET",
                            "id": "directory.groups.aliases.list",
                            "path": "groups/{groupKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.group",
                                "https://www.googleapis.com/auth/admin.directory.group.readonly"
                            ],
                            "supportsSubscription": true
                        }
                    }
                }
            }
        },
        "members": {
            "methods": {
                "delete": {
                    "description": "Remove membership.",
                    "httpMethod": "DELETE",
                    "id": "directory.members.delete",
                    "path": "groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                },
                "get": {
                    "description": "Retrieve Group Member",
                    "httpMethod": "GET",
                    "id": "directory.members.get",
                    "path": "groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member",
                        "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "insert": {
                    "description": "Add user to the specified group.",
                    "httpMethod": "POST",
                    "id": "directory.members.insert",
                    "path": "groups/{groupKey}/members",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                },
                "list": {
                    "description": "Retrieve all members in a group (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.members.list",
                    "path": "groups/{groupKey}/members",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member",
                        "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "patch": {
                    "description": "Update membership of a user in the specified group. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.members.patch",
                    "path": "groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                },
                "update": {
                    "description": "Update membership of a user in the specified group.",
                    "httpMethod": "PUT",
                    "id": "directory.members.update",
                    "path": "groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                }
            }
        },
        "mobiledevices": {
            "methods": {
                "action": {
                    "description": "Take action on Mobile Device",
                    "httpMethod": "POST",
                    "id": "directory.mobiledevices.action",
                    "path": "customer/{customerId}/devices/mobile/{resourceId}/action",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.action"
                    ]
                },
                "delete": {
                    "description": "Delete Mobile Device",
                    "httpMethod": "DELETE",
                    "id": "directory.mobiledevices.delete",
                    "path": "customer/{customerId}/devices/mobile/{resourceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile"
                    ]
                },
                "get": {
                    "description": "Retrieve Mobile Device",
                    "httpMethod": "GET",
                    "id": "directory.mobiledevices.get",
                    "path": "customer/{customerId}/devices/mobile/{resourceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieve all Mobile Devices of a customer (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.mobiledevices.list",
                    "path": "customer/{customerId}/devices/mobile",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
                    ]
                }
            }
        },
        "notifications": {
            "methods": {
                "delete": {
                    "description": "Deletes a notification",
                    "httpMethod": "DELETE",
                    "id": "directory.notifications.delete",
                    "path": "customer/{customer}/notifications/{notificationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.notifications"
                    ]
                },
                "get": {
                    "description": "Retrieves a notification.",
                    "httpMethod": "GET",
                    "id": "directory.notifications.get",
                    "path": "customer/{customer}/notifications/{notificationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.notifications"
                    ]
                },
                "list": {
                    "description": "Retrieves a list of notifications.",
                    "httpMethod": "GET",
                    "id": "directory.notifications.list",
                    "path": "customer/{customer}/notifications",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.notifications"
                    ]
                },
                "patch": {
                    "description": "Updates a notification. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.notifications.patch",
                    "path": "customer/{customer}/notifications/{notificationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.notifications"
                    ]
                },
                "update": {
                    "description": "Updates a notification.",
                    "httpMethod": "PUT",
                    "id": "directory.notifications.update",
                    "path": "customer/{customer}/notifications/{notificationId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.notifications"
                    ]
                }
            }
        },
        "orgunits": {
            "methods": {
                "delete": {
                    "description": "Remove Organization Unit",
                    "httpMethod": "DELETE",
                    "id": "directory.orgunits.delete",
                    "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "get": {
                    "description": "Retrieve Organization Unit",
                    "httpMethod": "GET",
                    "id": "directory.orgunits.get",
                    "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit",
                        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
                    ]
                },
                "insert": {
                    "description": "Add Organization Unit",
                    "httpMethod": "POST",
                    "id": "directory.orgunits.insert",
                    "path": "customer/{customerId}/orgunits",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "list": {
                    "description": "Retrieve all Organization Units",
                    "httpMethod": "GET",
                    "id": "directory.orgunits.list",
                    "path": "customer/{customerId}/orgunits",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit",
                        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
                    ]
                },
                "patch": {
                    "description": "Update Organization Unit. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.orgunits.patch",
                    "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "update": {
                    "description": "Update Organization Unit",
                    "httpMethod": "PUT",
                    "id": "directory.orgunits.update",
                    "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                }
            }
        },
        "schemas": {
            "methods": {
                "delete": {
                    "description": "Delete schema",
                    "httpMethod": "DELETE",
                    "id": "directory.schemas.delete",
                    "path": "customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                },
                "get": {
                    "description": "Retrieve schema",
                    "httpMethod": "GET",
                    "id": "directory.schemas.get",
                    "path": "customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema",
                        "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
                    ]
                },
                "insert": {
                    "description": "Create schema.",
                    "httpMethod": "POST",
                    "id": "directory.schemas.insert",
                    "path": "customer/{customerId}/schemas",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                },
                "list": {
                    "description": "Retrieve all schemas for a customer",
                    "httpMethod": "GET",
                    "id": "directory.schemas.list",
                    "path": "customer/{customerId}/schemas",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema",
                        "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
                    ]
                },
                "patch": {
                    "description": "Update schema. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.schemas.patch",
                    "path": "customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                },
                "update": {
                    "description": "Update schema",
                    "httpMethod": "PUT",
                    "id": "directory.schemas.update",
                    "path": "customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                }
            }
        },
        "tokens": {
            "methods": {
                "delete": {
                    "description": "Delete all access tokens issued by a user for an application.",
                    "httpMethod": "DELETE",
                    "id": "directory.tokens.delete",
                    "path": "users/{userKey}/tokens/{clientId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "get": {
                    "description": "Get information about an access token issued by a user.",
                    "httpMethod": "GET",
                    "id": "directory.tokens.get",
                    "path": "users/{userKey}/tokens/{clientId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "list": {
                    "description": "Returns the set of tokens specified user has issued to 3rd party applications.",
                    "httpMethod": "GET",
                    "id": "directory.tokens.list",
                    "path": "users/{userKey}/tokens",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        },
        "users": {
            "methods": {
                "delete": {
                    "description": "Delete user",
                    "httpMethod": "DELETE",
                    "id": "directory.users.delete",
                    "path": "users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "get": {
                    "description": "retrieve user",
                    "httpMethod": "GET",
                    "id": "directory.users.get",
                    "path": "users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly"
                    ]
                },
                "insert": {
                    "description": "create user.",
                    "httpMethod": "POST",
                    "id": "directory.users.insert",
                    "path": "users",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "list": {
                    "description": "Retrieve either deleted users or all users in a domain (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.users.list",
                    "path": "users",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly"
                    ],
                    "supportsSubscription": true
                },
                "makeAdmin": {
                    "description": "change admin status of a user",
                    "httpMethod": "POST",
                    "id": "directory.users.makeAdmin",
                    "path": "users/{userKey}/makeAdmin",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "patch": {
                    "description": "update user. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "directory.users.patch",
                    "path": "users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "undelete": {
                    "description": "Undelete a deleted user",
                    "httpMethod": "POST",
                    "id": "directory.users.undelete",
                    "path": "users/{userKey}/undelete",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "update": {
                    "description": "update user",
                    "httpMethod": "PUT",
                    "id": "directory.users.update",
                    "path": "users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "watch": {
                    "description": "Watch for changes in users list",
                    "httpMethod": "POST",
                    "id": "directory.users.watch",
                    "path": "users/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly"
                    ],
                    "supportsSubscription": true
                }
            },
            "resources": {
                "aliases": {
                    "methods": {
                        "delete": {
                            "description": "Remove a alias for the user",
                            "httpMethod": "DELETE",
                            "id": "directory.users.aliases.delete",
                            "path": "users/{userKey}/aliases/{alias}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias"
                            ]
                        },
                        "insert": {
                            "description": "Add a alias for the user",
                            "httpMethod": "POST",
                            "id": "directory.users.aliases.insert",
                            "path": "users/{userKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias"
                            ]
                        },
                        "list": {
                            "description": "List all aliases for a user",
                            "httpMethod": "GET",
                            "id": "directory.users.aliases.list",
                            "path": "users/{userKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias",
                                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                                "https://www.googleapis.com/auth/admin.directory.user.readonly"
                            ],
                            "supportsSubscription": true
                        },
                        "watch": {
                            "description": "Watch for changes in user aliases list",
                            "httpMethod": "POST",
                            "id": "directory.users.aliases.watch",
                            "path": "users/{userKey}/aliases/watch",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias",
                                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                                "https://www.googleapis.com/auth/admin.directory.user.readonly"
                            ],
                            "supportsSubscription": true
                        }
                    }
                },
                "photos": {
                    "methods": {
                        "delete": {
                            "description": "Remove photos for the user",
                            "httpMethod": "DELETE",
                            "id": "directory.users.photos.delete",
                            "path": "users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user"
                            ]
                        },
                        "get": {
                            "description": "Retrieve photo of a user",
                            "httpMethod": "GET",
                            "id": "directory.users.photos.get",
                            "path": "users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.readonly"
                            ]
                        },
                        "patch": {
                            "description": "Add a photo for the user. This method supports patch semantics.",
                            "httpMethod": "PATCH",
                            "id": "directory.users.photos.patch",
                            "path": "users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user"
                            ]
                        },
                        "update": {
                            "description": "Add a photo for the user",
                            "httpMethod": "PUT",
                            "id": "directory.users.photos.update",
                            "path": "users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user"
                            ]
                        }
                    }
                }
            }
        },
        "verificationCodes": {
            "methods": {
                "generate": {
                    "description": "Generate new backup verification codes for the user.",
                    "httpMethod": "POST",
                    "id": "directory.verificationCodes.generate",
                    "path": "users/{userKey}/verificationCodes/generate",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "invalidate": {
                    "description": "Invalidate the current backup verification codes for the user.",
                    "httpMethod": "POST",
                    "id": "directory.verificationCodes.invalidate",
                    "path": "users/{userKey}/verificationCodes/invalidate",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "list": {
                    "description": "Returns the current set of valid backup verification codes for the specified user.",
                    "httpMethod": "GET",
                    "id": "directory.verificationCodes.list",
                    "path": "users/{userKey}/verificationCodes",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        }
    },
    "revision": "20150309",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "admin/directory/v1/",
    "title": "Admin Directory API",
    "version": "directory_v1"
}