{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/admin.directory.user.alias": {
                    "description": "View and manage user aliases on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.orgunit": {
                    "description": "View and manage organization units on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.device.mobile": {
                    "description": "View and manage your mobile devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.user": {
                    "description": "View and manage the provisioning of users on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.rolemanagement": {
                    "description": "Manage delegated admin roles for your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.group.member.readonly": {
                    "description": "View group subscriptions on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user.readonly": {
                    "description": "View users on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.userschema": {
                    "description": "View and manage the provisioning of user schemas on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.domain.readonly": {
                    "description": "View domains related to your customers"
                },
                "https://www.googleapis.com/auth/cloud-platform": {
                    "description": "View and manage your data across Google Cloud Platform services"
                },
                "https://www.googleapis.com/auth/admin.directory.customer.readonly": {
                    "description": "View customer related information"
                },
                "https://www.googleapis.com/auth/admin.directory.userschema.readonly": {
                    "description": "View user schemas on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly": {
                    "description": "View your mobile devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.group.member": {
                    "description": "View and manage group subscriptions on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.orgunit.readonly": {
                    "description": "View organization units on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly": {
                    "description": "View calendar resources on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.device.chromeos": {
                    "description": "View and manage your Chrome OS devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.resource.calendar": {
                    "description": "View and manage the provisioning of calendar resources on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.group": {
                    "description": "View and manage the provisioning of groups on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.customer": {
                    "description": "View and manage customer related information"
                },
                "https://www.googleapis.com/auth/admin.directory.device.mobile.action": {
                    "description": "Manage your mobile devices by performing administrative tasks"
                },
                "https://www.googleapis.com/auth/admin.directory.domain": {
                    "description": "View and manage the provisioning of domains for your customers"
                },
                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly": {
                    "description": "View user aliases on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.user.security": {
                    "description": "Manage data access permissions for users on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly": {
                    "description": "View your Chrome OS devices' metadata"
                },
                "https://www.googleapis.com/auth/admin.directory.group.readonly": {
                    "description": "View groups on your domain"
                },
                "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly": {
                    "description": "View delegated admin roles for your domain"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://www.googleapis.com/",
    "batchPath": "batch/admin/directory_v1",
    "canonicalName": "directory",
    "description": "Admin SDK lets administrators of enterprise domains to view and manage resources like user, groups etc. It also provides audit and usage reports of domain.",
    "discoveryVersion": "v1",
    "documentationLink": "http://developers.google.com/admin-sdk/",
    "id": "admin:directory_v1",
    "kind": "discovery#restDescription",
    "name": "admin",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "packagePath": "admin",
    "protocol": "rest",
    "resources": {
        "domainAliases": {
            "methods": {
                "insert": {
                    "description": "Inserts a domain alias of the customer.",
                    "httpMethod": "POST",
                    "id": "directory.domainAliases.insert",
                    "path": "admin/directory/v1/customer/{customer}/domainaliases",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain"
                    ]
                },
                "get": {
                    "description": "Retrieves a domain alias of the customer.",
                    "httpMethod": "GET",
                    "id": "directory.domainAliases.get",
                    "path": "admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain",
                        "https://www.googleapis.com/auth/admin.directory.domain.readonly"
                    ]
                },
                "delete": {
                    "description": "Deletes a domain Alias of the customer.",
                    "httpMethod": "DELETE",
                    "id": "directory.domainAliases.delete",
                    "path": "admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain"
                    ]
                },
                "list": {
                    "description": "Lists the domain aliases of the customer.",
                    "httpMethod": "GET",
                    "id": "directory.domainAliases.list",
                    "path": "admin/directory/v1/customer/{customer}/domainaliases",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain",
                        "https://www.googleapis.com/auth/admin.directory.domain.readonly"
                    ]
                }
            }
        },
        "users": {
            "methods": {
                "undelete": {
                    "description": "Undelete a deleted user",
                    "httpMethod": "POST",
                    "id": "directory.users.undelete",
                    "path": "admin/directory/v1/users/{userKey}/undelete",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "watch": {
                    "description": "Watch for changes in users list",
                    "httpMethod": "POST",
                    "id": "directory.users.watch",
                    "path": "admin/directory/v1/users/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "get": {
                    "description": "retrieve user",
                    "httpMethod": "GET",
                    "id": "directory.users.get",
                    "path": "admin/directory/v1/users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly"
                    ]
                },
                "insert": {
                    "description": "create user.",
                    "httpMethod": "POST",
                    "id": "directory.users.insert",
                    "path": "admin/directory/v1/users",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "makeAdmin": {
                    "description": "change admin status of a user",
                    "httpMethod": "POST",
                    "id": "directory.users.makeAdmin",
                    "path": "admin/directory/v1/users/{userKey}/makeAdmin",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "delete": {
                    "description": "Delete user",
                    "httpMethod": "DELETE",
                    "id": "directory.users.delete",
                    "path": "admin/directory/v1/users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "patch": {
                    "description": "Patch Users via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.users.patch",
                    "path": "admin/directory/v1/users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "update": {
                    "description": "update user",
                    "httpMethod": "PUT",
                    "id": "directory.users.update",
                    "path": "admin/directory/v1/users/{userKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user"
                    ]
                },
                "list": {
                    "description": "Retrieve either deleted users or all users in a domain (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.users.list",
                    "path": "admin/directory/v1/users",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                },
                "signOut": {
                    "description": "Sign a user out of all web and device sessions and reset their sign-in cookies. User will have to sign in by authenticating again.",
                    "httpMethod": "POST",
                    "id": "directory.users.signOut",
                    "path": "admin/directory/v1/users/{userKey}/signOut",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            },
            "resources": {
                "aliases": {
                    "methods": {
                        "list": {
                            "description": "List all aliases for a user",
                            "httpMethod": "GET",
                            "id": "directory.users.aliases.list",
                            "path": "admin/directory/v1/users/{userKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias",
                                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                                "https://www.googleapis.com/auth/admin.directory.user.readonly"
                            ]
                        },
                        "insert": {
                            "description": "Add a alias for the user",
                            "httpMethod": "POST",
                            "id": "directory.users.aliases.insert",
                            "path": "admin/directory/v1/users/{userKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias"
                            ]
                        },
                        "delete": {
                            "description": "Remove a alias for the user",
                            "httpMethod": "DELETE",
                            "id": "directory.users.aliases.delete",
                            "path": "admin/directory/v1/users/{userKey}/aliases/{alias}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias"
                            ]
                        },
                        "watch": {
                            "description": "Watch for changes in users list",
                            "httpMethod": "POST",
                            "id": "directory.users.aliases.watch",
                            "path": "admin/directory/v1/users/{userKey}/aliases/watch",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.alias",
                                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                                "https://www.googleapis.com/auth/admin.directory.user.readonly"
                            ]
                        }
                    }
                },
                "photos": {
                    "methods": {
                        "patch": {
                            "description": "Patch Photo via Apiary Patch Orchestration",
                            "httpMethod": "PATCH",
                            "id": "directory.users.photos.patch",
                            "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user"
                            ]
                        },
                        "update": {
                            "description": "Add a photo for the user",
                            "httpMethod": "PUT",
                            "id": "directory.users.photos.update",
                            "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user"
                            ]
                        },
                        "delete": {
                            "description": "Remove photos for the user",
                            "httpMethod": "DELETE",
                            "id": "directory.users.photos.delete",
                            "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user"
                            ]
                        },
                        "get": {
                            "description": "Retrieve photo of a user",
                            "httpMethod": "GET",
                            "id": "directory.users.photos.get",
                            "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.user",
                                "https://www.googleapis.com/auth/admin.directory.user.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "orgunits": {
            "methods": {
                "patch": {
                    "description": "Patch organization unit via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.orgunits.patch",
                    "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "insert": {
                    "description": "Add organizational unit",
                    "httpMethod": "POST",
                    "id": "directory.orgunits.insert",
                    "path": "admin/directory/v1/customer/{customerId}/orgunits",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "update": {
                    "description": "Update organizational unit",
                    "httpMethod": "PUT",
                    "id": "directory.orgunits.update",
                    "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "delete": {
                    "description": "Remove organizational unit",
                    "httpMethod": "DELETE",
                    "id": "directory.orgunits.delete",
                    "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit"
                    ]
                },
                "list": {
                    "description": "Retrieve all organizational units",
                    "httpMethod": "GET",
                    "id": "directory.orgunits.list",
                    "path": "admin/directory/v1/customer/{customerId}/orgunits",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit",
                        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
                    ]
                },
                "get": {
                    "description": "Retrieve organizational unit",
                    "httpMethod": "GET",
                    "id": "directory.orgunits.get",
                    "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.orgunit",
                        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
                    ]
                }
            }
        },
        "resources": {
            "resources": {
                "calendars": {
                    "methods": {
                        "get": {
                            "description": "Retrieves a calendar resource.",
                            "httpMethod": "GET",
                            "id": "directory.resources.calendars.get",
                            "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
                            ]
                        },
                        "update": {
                            "description": "Updates a calendar resource. This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.",
                            "httpMethod": "PUT",
                            "id": "directory.resources.calendars.update",
                            "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "patch": {
                            "description": "Patches a calendar resource via Apiary Patch Orchestration.",
                            "httpMethod": "PATCH",
                            "id": "directory.resources.calendars.patch",
                            "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "delete": {
                            "description": "Deletes a calendar resource.",
                            "httpMethod": "DELETE",
                            "id": "directory.resources.calendars.delete",
                            "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "list": {
                            "description": "Retrieves a list of calendar resources for an account.",
                            "httpMethod": "GET",
                            "id": "directory.resources.calendars.list",
                            "path": "admin/directory/v1/customer/{customer}/resources/calendars",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
                            ]
                        },
                        "insert": {
                            "description": "Inserts a calendar resource.",
                            "httpMethod": "POST",
                            "id": "directory.resources.calendars.insert",
                            "path": "admin/directory/v1/customer/{customer}/resources/calendars",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        }
                    }
                },
                "buildings": {
                    "methods": {
                        "update": {
                            "description": "Updates a building.",
                            "httpMethod": "PUT",
                            "id": "directory.resources.buildings.update",
                            "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "patch": {
                            "description": "Patches a building via Apiary Patch Orchestration.",
                            "httpMethod": "PATCH",
                            "id": "directory.resources.buildings.patch",
                            "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "insert": {
                            "description": "Inserts a building.",
                            "httpMethod": "POST",
                            "id": "directory.resources.buildings.insert",
                            "path": "admin/directory/v1/customer/{customer}/resources/buildings",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "get": {
                            "description": "Retrieves a building.",
                            "httpMethod": "GET",
                            "id": "directory.resources.buildings.get",
                            "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
                            ]
                        },
                        "delete": {
                            "description": "Deletes a building.",
                            "httpMethod": "DELETE",
                            "id": "directory.resources.buildings.delete",
                            "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "list": {
                            "description": "Retrieves a list of buildings for an account.",
                            "httpMethod": "GET",
                            "id": "directory.resources.buildings.list",
                            "path": "admin/directory/v1/customer/{customer}/resources/buildings",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
                            ]
                        }
                    }
                },
                "features": {
                    "methods": {
                        "delete": {
                            "description": "Deletes a feature.",
                            "httpMethod": "DELETE",
                            "id": "directory.resources.features.delete",
                            "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "list": {
                            "description": "Retrieves a list of features for an account.",
                            "httpMethod": "GET",
                            "id": "directory.resources.features.list",
                            "path": "admin/directory/v1/customer/{customer}/resources/features",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
                            ]
                        },
                        "rename": {
                            "description": "Renames a feature.",
                            "httpMethod": "POST",
                            "id": "directory.resources.features.rename",
                            "path": "admin/directory/v1/customer/{customer}/resources/features/{oldName}/rename",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "update": {
                            "description": "Updates a feature.",
                            "httpMethod": "PUT",
                            "id": "directory.resources.features.update",
                            "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "insert": {
                            "description": "Inserts a feature.",
                            "httpMethod": "POST",
                            "id": "directory.resources.features.insert",
                            "path": "admin/directory/v1/customer/{customer}/resources/features",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "patch": {
                            "description": "Patches a feature via Apiary Patch Orchestration.",
                            "httpMethod": "PATCH",
                            "id": "directory.resources.features.patch",
                            "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
                            ]
                        },
                        "get": {
                            "description": "Retrieves a feature.",
                            "httpMethod": "GET",
                            "id": "directory.resources.features.get",
                            "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "twoStepVerification": {
            "methods": {
                "turnOff": {
                    "description": "Turn off 2-Step Verification for user.",
                    "httpMethod": "POST",
                    "id": "directory.twoStepVerification.turnOff",
                    "path": "admin/directory/v1/users/{userKey}/twoStepVerification/turnOff",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        },
        "tokens": {
            "methods": {
                "get": {
                    "description": "Get information about an access token issued by a user.",
                    "httpMethod": "GET",
                    "id": "directory.tokens.get",
                    "path": "admin/directory/v1/users/{userKey}/tokens/{clientId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "list": {
                    "description": "Returns the set of tokens specified user has issued to 3rd party applications.",
                    "httpMethod": "GET",
                    "id": "directory.tokens.list",
                    "path": "admin/directory/v1/users/{userKey}/tokens",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "delete": {
                    "description": "Delete all access tokens issued by a user for an application.",
                    "httpMethod": "DELETE",
                    "id": "directory.tokens.delete",
                    "path": "admin/directory/v1/users/{userKey}/tokens/{clientId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        },
        "customers": {
            "methods": {
                "patch": {
                    "description": "Patch Customers via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.customers.patch",
                    "path": "admin/directory/v1/customers/{customerKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.customer"
                    ]
                },
                "get": {
                    "description": "Retrieves a customer.",
                    "httpMethod": "GET",
                    "id": "directory.customers.get",
                    "path": "admin/directory/v1/customers/{customerKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.customer",
                        "https://www.googleapis.com/auth/admin.directory.customer.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a customer.",
                    "httpMethod": "PUT",
                    "id": "directory.customers.update",
                    "path": "admin/directory/v1/customers/{customerKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.customer"
                    ]
                }
            }
        },
        "domains": {
            "methods": {
                "list": {
                    "description": "Lists the domains of the customer.",
                    "httpMethod": "GET",
                    "id": "directory.domains.list",
                    "path": "admin/directory/v1/customer/{customer}/domains",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain",
                        "https://www.googleapis.com/auth/admin.directory.domain.readonly"
                    ]
                },
                "delete": {
                    "description": "Deletes a domain of the customer.",
                    "httpMethod": "DELETE",
                    "id": "directory.domains.delete",
                    "path": "admin/directory/v1/customer/{customer}/domains/{domainName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain"
                    ]
                },
                "insert": {
                    "description": "Inserts a domain of the customer.",
                    "httpMethod": "POST",
                    "id": "directory.domains.insert",
                    "path": "admin/directory/v1/customer/{customer}/domains",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain"
                    ]
                },
                "get": {
                    "description": "Retrieves a domain of the customer.",
                    "httpMethod": "GET",
                    "id": "directory.domains.get",
                    "path": "admin/directory/v1/customer/{customer}/domains/{domainName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.domain",
                        "https://www.googleapis.com/auth/admin.directory.domain.readonly"
                    ]
                }
            }
        },
        "mobiledevices": {
            "methods": {
                "delete": {
                    "description": "Delete Mobile Device",
                    "httpMethod": "DELETE",
                    "id": "directory.mobiledevices.delete",
                    "path": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile"
                    ]
                },
                "get": {
                    "description": "Retrieve Mobile Device",
                    "httpMethod": "GET",
                    "id": "directory.mobiledevices.get",
                    "path": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieve all Mobile Devices of a customer (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.mobiledevices.list",
                    "path": "admin/directory/v1/customer/{customerId}/devices/mobile",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
                    ]
                },
                "action": {
                    "description": "Take action on Mobile Device",
                    "httpMethod": "POST",
                    "id": "directory.mobiledevices.action",
                    "path": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}/action",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.mobile",
                        "https://www.googleapis.com/auth/admin.directory.device.mobile.action"
                    ]
                }
            }
        },
        "asps": {
            "methods": {
                "list": {
                    "description": "List the ASPs issued by a user.",
                    "httpMethod": "GET",
                    "id": "directory.asps.list",
                    "path": "admin/directory/v1/users/{userKey}/asps",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "get": {
                    "description": "Get information about an ASP issued by a user.",
                    "httpMethod": "GET",
                    "id": "directory.asps.get",
                    "path": "admin/directory/v1/users/{userKey}/asps/{codeId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "delete": {
                    "description": "Delete an ASP issued by a user.",
                    "httpMethod": "DELETE",
                    "id": "directory.asps.delete",
                    "path": "admin/directory/v1/users/{userKey}/asps/{codeId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        },
        "schemas": {
            "methods": {
                "get": {
                    "description": "Retrieve schema",
                    "httpMethod": "GET",
                    "id": "directory.schemas.get",
                    "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema",
                        "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
                    ]
                },
                "update": {
                    "description": "Update schema",
                    "httpMethod": "PUT",
                    "id": "directory.schemas.update",
                    "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                },
                "insert": {
                    "description": "Create schema.",
                    "httpMethod": "POST",
                    "id": "directory.schemas.insert",
                    "path": "admin/directory/v1/customer/{customerId}/schemas",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                },
                "list": {
                    "description": "Retrieve all schemas for a customer",
                    "httpMethod": "GET",
                    "id": "directory.schemas.list",
                    "path": "admin/directory/v1/customer/{customerId}/schemas",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema",
                        "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
                    ]
                },
                "patch": {
                    "description": "Patch Schema via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.schemas.patch",
                    "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                },
                "delete": {
                    "description": "Delete schema",
                    "httpMethod": "DELETE",
                    "id": "directory.schemas.delete",
                    "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.userschema"
                    ]
                }
            }
        },
        "members": {
            "methods": {
                "insert": {
                    "description": "Add user to the specified group.",
                    "httpMethod": "POST",
                    "id": "directory.members.insert",
                    "path": "admin/directory/v1/groups/{groupKey}/members",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                },
                "hasMember": {
                    "description": "Checks whether the given user is a member of the group. Membership can be direct or nested.",
                    "httpMethod": "GET",
                    "id": "directory.members.hasMember",
                    "path": "admin/directory/v1/groups/{groupKey}/hasMember/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member",
                        "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "delete": {
                    "description": "Remove membership.",
                    "httpMethod": "DELETE",
                    "id": "directory.members.delete",
                    "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                },
                "update": {
                    "description": "Update membership of a user in the specified group.",
                    "httpMethod": "PUT",
                    "id": "directory.members.update",
                    "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                },
                "list": {
                    "description": "Retrieve all members in a group (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.members.list",
                    "path": "admin/directory/v1/groups/{groupKey}/members",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member",
                        "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "get": {
                    "description": "Retrieve Group Member",
                    "httpMethod": "GET",
                    "id": "directory.members.get",
                    "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member",
                        "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "patch": {
                    "description": "Patch Member via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.members.patch",
                    "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.member"
                    ]
                }
            }
        },
        "roleAssignments": {
            "methods": {
                "get": {
                    "description": "Retrieve a role assignment.",
                    "httpMethod": "GET",
                    "id": "directory.roleAssignments.get",
                    "path": "admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement",
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieves a paginated list of all roleAssignments.",
                    "httpMethod": "GET",
                    "id": "directory.roleAssignments.list",
                    "path": "admin/directory/v1/customer/{customer}/roleassignments",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement",
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
                    ]
                },
                "delete": {
                    "description": "Deletes a role assignment.",
                    "httpMethod": "DELETE",
                    "id": "directory.roleAssignments.delete",
                    "path": "admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement"
                    ]
                },
                "insert": {
                    "description": "Creates a role assignment.",
                    "httpMethod": "POST",
                    "id": "directory.roleAssignments.insert",
                    "path": "admin/directory/v1/customer/{customer}/roleassignments",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement"
                    ]
                }
            }
        },
        "verificationCodes": {
            "methods": {
                "list": {
                    "description": "Returns the current set of valid backup verification codes for the specified user.",
                    "httpMethod": "GET",
                    "id": "directory.verificationCodes.list",
                    "path": "admin/directory/v1/users/{userKey}/verificationCodes",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "invalidate": {
                    "description": "Invalidate the current backup verification codes for the user.",
                    "httpMethod": "POST",
                    "id": "directory.verificationCodes.invalidate",
                    "path": "admin/directory/v1/users/{userKey}/verificationCodes/invalidate",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                },
                "generate": {
                    "description": "Generate new backup verification codes for the user.",
                    "httpMethod": "POST",
                    "id": "directory.verificationCodes.generate",
                    "path": "admin/directory/v1/users/{userKey}/verificationCodes/generate",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user.security"
                    ]
                }
            }
        },
        "privileges": {
            "methods": {
                "list": {
                    "description": "Retrieves a paginated list of all privileges for a customer.",
                    "httpMethod": "GET",
                    "id": "directory.privileges.list",
                    "path": "admin/directory/v1/customer/{customer}/roles/ALL/privileges",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement",
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
                    ]
                }
            }
        },
        "roles": {
            "methods": {
                "delete": {
                    "description": "Deletes a role.",
                    "httpMethod": "DELETE",
                    "id": "directory.roles.delete",
                    "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement"
                    ]
                },
                "insert": {
                    "description": "Creates a role.",
                    "httpMethod": "POST",
                    "id": "directory.roles.insert",
                    "path": "admin/directory/v1/customer/{customer}/roles",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement"
                    ]
                },
                "patch": {
                    "description": "Patch role via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.roles.patch",
                    "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement"
                    ]
                },
                "list": {
                    "description": "Retrieves a paginated list of all the roles in a domain.",
                    "httpMethod": "GET",
                    "id": "directory.roles.list",
                    "path": "admin/directory/v1/customer/{customer}/roles",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement",
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
                    ]
                },
                "get": {
                    "description": "Retrieves a role.",
                    "httpMethod": "GET",
                    "id": "directory.roles.get",
                    "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement",
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a role.",
                    "httpMethod": "PUT",
                    "id": "directory.roles.update",
                    "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.rolemanagement"
                    ]
                }
            }
        },
        "groups": {
            "methods": {
                "list": {
                    "description": "Retrieve all groups of a domain or of a user given a userKey (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.groups.list",
                    "path": "admin/directory/v1/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "patch": {
                    "description": "Patch Groups via Apiary Patch Orchestration",
                    "httpMethod": "PATCH",
                    "id": "directory.groups.patch",
                    "path": "admin/directory/v1/groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                },
                "insert": {
                    "description": "Create Group",
                    "httpMethod": "POST",
                    "id": "directory.groups.insert",
                    "path": "admin/directory/v1/groups",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                },
                "get": {
                    "description": "Retrieve Group",
                    "httpMethod": "GET",
                    "id": "directory.groups.get",
                    "path": "admin/directory/v1/groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group",
                        "https://www.googleapis.com/auth/admin.directory.group.readonly"
                    ]
                },
                "update": {
                    "description": "Update Group",
                    "httpMethod": "PUT",
                    "id": "directory.groups.update",
                    "path": "admin/directory/v1/groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                },
                "delete": {
                    "description": "Delete Group",
                    "httpMethod": "DELETE",
                    "id": "directory.groups.delete",
                    "path": "admin/directory/v1/groups/{groupKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.group"
                    ]
                }
            },
            "resources": {
                "aliases": {
                    "methods": {
                        "list": {
                            "description": "List all aliases for a group",
                            "httpMethod": "GET",
                            "id": "directory.groups.aliases.list",
                            "path": "admin/directory/v1/groups/{groupKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.group",
                                "https://www.googleapis.com/auth/admin.directory.group.readonly"
                            ]
                        },
                        "insert": {
                            "description": "Add a alias for the group",
                            "httpMethod": "POST",
                            "id": "directory.groups.aliases.insert",
                            "path": "admin/directory/v1/groups/{groupKey}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.group"
                            ]
                        },
                        "delete": {
                            "description": "Remove a alias for the group",
                            "httpMethod": "DELETE",
                            "id": "directory.groups.aliases.delete",
                            "path": "admin/directory/v1/groups/{groupKey}/aliases/{alias}",
                            "scopes": [
                                "https://www.googleapis.com/auth/admin.directory.group"
                            ]
                        }
                    }
                }
            }
        },
        "chromeosdevices": {
            "methods": {
                "get": {
                    "description": "Retrieve Chrome OS Device",
                    "httpMethod": "GET",
                    "id": "directory.chromeosdevices.get",
                    "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos",
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
                    ]
                },
                "update": {
                    "description": "Update Chrome OS Device",
                    "httpMethod": "PUT",
                    "id": "directory.chromeosdevices.update",
                    "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                    ]
                },
                "patch": {
                    "description": "Patch Chrome OS Device",
                    "httpMethod": "PATCH",
                    "id": "directory.chromeosdevices.patch",
                    "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                    ]
                },
                "action": {
                    "description": "Take action on Chrome OS Device",
                    "httpMethod": "POST",
                    "id": "directory.chromeosdevices.action",
                    "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{resourceId}/action",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                    ]
                },
                "moveDevicesToOu": {
                    "description": "Move or insert multiple Chrome OS Devices to organizational unit",
                    "httpMethod": "POST",
                    "id": "directory.chromeosdevices.moveDevicesToOu",
                    "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/moveDevicesToOu",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                    ]
                },
                "list": {
                    "description": "Retrieve all Chrome OS Devices of a customer (paginated)",
                    "httpMethod": "GET",
                    "id": "directory.chromeosdevices.list",
                    "path": "admin/directory/v1/customer/{customerId}/devices/chromeos",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos",
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
                    ]
                }
            }
        },
        "channels": {
            "methods": {
                "stop": {
                    "description": "Stop watching resources through this channel.",
                    "httpMethod": "POST",
                    "id": "admin.channels.stop",
                    "path": "admin/directory_v1/channels/stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.user",
                        "https://www.googleapis.com/auth/admin.directory.user.alias",
                        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                        "https://www.googleapis.com/auth/admin.directory.user.readonly",
                        "https://www.googleapis.com/auth/cloud-platform"
                    ]
                }
            }
        }
    },
    "revision": "20201006",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "",
    "title": "Admin SDK",
    "version": "directory_v1"
}