{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/blogger": {
                    "description": "Manage your Blogger account"
                },
                "https://www.googleapis.com/auth/blogger.readonly": {
                    "description": "View your Blogger account"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://blogger.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Blogger",
    "description": "The Blogger API provides access to posts, comments and pages of a Blogger blog.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/blogger/docs/3.0/getting_started",
    "id": "blogger:v3",
    "kind": "discovery#restDescription",
    "name": "blogger",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "posts": {
            "methods": {
                "patch": {
                    "description": "Patches a post.",
                    "httpMethod": "PATCH",
                    "id": "blogger.posts.patch",
                    "path": "v3/blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "search": {
                    "description": "Searches for posts matching given query terms in the specified blog.",
                    "httpMethod": "GET",
                    "id": "blogger.posts.search",
                    "path": "v3/blogs/{blogId}/posts/search",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "delete": {
                    "description": "Deletes a post by blog id and post id.",
                    "httpMethod": "DELETE",
                    "id": "blogger.posts.delete",
                    "path": "v3/blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "get": {
                    "description": "Gets a post by blog id and post id",
                    "httpMethod": "GET",
                    "id": "blogger.posts.get",
                    "path": "v3/blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a post by blog id and post id.",
                    "httpMethod": "PUT",
                    "id": "blogger.posts.update",
                    "path": "v3/blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "publish": {
                    "description": "Publishes a post.",
                    "httpMethod": "POST",
                    "id": "blogger.posts.publish",
                    "path": "v3/blogs/{blogId}/posts/{postId}/publish",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "getByPath": {
                    "description": "Gets a post by path.",
                    "httpMethod": "GET",
                    "id": "blogger.posts.getByPath",
                    "path": "v3/blogs/{blogId}/posts/bypath",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "revert": {
                    "description": "Reverts a published or scheduled post to draft state.",
                    "httpMethod": "POST",
                    "id": "blogger.posts.revert",
                    "path": "v3/blogs/{blogId}/posts/{postId}/revert",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "insert": {
                    "description": "Inserts a post.",
                    "httpMethod": "POST",
                    "id": "blogger.posts.insert",
                    "path": "v3/blogs/{blogId}/posts",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "list": {
                    "description": "Lists posts.",
                    "httpMethod": "GET",
                    "id": "blogger.posts.list",
                    "path": "v3/blogs/{blogId}/posts",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "pageViews": {
            "methods": {
                "get": {
                    "description": "Gets page views by blog id.",
                    "httpMethod": "GET",
                    "id": "blogger.pageViews.get",
                    "path": "v3/blogs/{blogId}/pageviews",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                }
            }
        },
        "blogs": {
            "methods": {
                "listByUser": {
                    "description": "Lists blogs by user.",
                    "httpMethod": "GET",
                    "id": "blogger.blogs.listByUser",
                    "path": "v3/users/{userId}/blogs",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "getByUrl": {
                    "description": "Gets a blog by url.",
                    "httpMethod": "GET",
                    "id": "blogger.blogs.getByUrl",
                    "path": "v3/blogs/byurl",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "get": {
                    "description": "Gets a blog by id.",
                    "httpMethod": "GET",
                    "id": "blogger.blogs.get",
                    "path": "v3/blogs/{blogId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "pages": {
            "methods": {
                "revert": {
                    "description": "Reverts a published or scheduled page to draft state.",
                    "httpMethod": "POST",
                    "id": "blogger.pages.revert",
                    "path": "v3/blogs/{blogId}/pages/{pageId}/revert",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "delete": {
                    "description": "Deletes a page by blog id and page id.",
                    "httpMethod": "DELETE",
                    "id": "blogger.pages.delete",
                    "path": "v3/blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "insert": {
                    "description": "Inserts a page.",
                    "httpMethod": "POST",
                    "id": "blogger.pages.insert",
                    "path": "v3/blogs/{blogId}/pages",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "publish": {
                    "description": "Publishes a page.",
                    "httpMethod": "POST",
                    "id": "blogger.pages.publish",
                    "path": "v3/blogs/{blogId}/pages/{pageId}/publish",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "update": {
                    "description": "Updates a page by blog id and page id.",
                    "httpMethod": "PUT",
                    "id": "blogger.pages.update",
                    "path": "v3/blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "get": {
                    "description": "Gets a page by blog id and page id.",
                    "httpMethod": "GET",
                    "id": "blogger.pages.get",
                    "path": "v3/blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "patch": {
                    "description": "Patches a page.",
                    "httpMethod": "PATCH",
                    "id": "blogger.pages.patch",
                    "path": "v3/blogs/{blogId}/pages/{pageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "list": {
                    "description": "Lists pages.",
                    "httpMethod": "GET",
                    "id": "blogger.pages.list",
                    "path": "v3/blogs/{blogId}/pages",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "removeContent": {
                    "description": "Removes the content of a comment by blog id, post id and comment id.",
                    "httpMethod": "POST",
                    "id": "blogger.comments.removeContent",
                    "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "get": {
                    "description": "Gets a comment by id.",
                    "httpMethod": "GET",
                    "id": "blogger.comments.get",
                    "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "delete": {
                    "description": "Deletes a comment by blog id, post id and comment id.",
                    "httpMethod": "DELETE",
                    "id": "blogger.comments.delete",
                    "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "markAsSpam": {
                    "description": "Marks a comment as spam by blog id, post id and comment id.",
                    "httpMethod": "POST",
                    "id": "blogger.comments.markAsSpam",
                    "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "approve": {
                    "description": "Marks a comment as not spam by blog id, post id and comment id.",
                    "httpMethod": "POST",
                    "id": "blogger.comments.approve",
                    "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger"
                    ]
                },
                "listByBlog": {
                    "description": "Lists comments by blog.",
                    "httpMethod": "GET",
                    "id": "blogger.comments.listByBlog",
                    "path": "v3/blogs/{blogId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "list": {
                    "description": "Lists comments.",
                    "httpMethod": "GET",
                    "id": "blogger.comments.list",
                    "path": "v3/blogs/{blogId}/posts/{postId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "postUserInfos": {
            "methods": {
                "get": {
                    "description": "Gets one post and user info pair, by post_id and user_id.",
                    "httpMethod": "GET",
                    "id": "blogger.postUserInfos.get",
                    "path": "v3/users/{userId}/blogs/{blogId}/posts/{postId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                },
                "list": {
                    "description": "Lists post and user info pairs.",
                    "httpMethod": "GET",
                    "id": "blogger.postUserInfos.list",
                    "path": "v3/users/{userId}/blogs/{blogId}/posts",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "users": {
            "methods": {
                "get": {
                    "description": "Gets one user by user_id.",
                    "httpMethod": "GET",
                    "id": "blogger.users.get",
                    "path": "v3/users/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        },
        "blogUserInfos": {
            "methods": {
                "get": {
                    "description": "Gets one blog and user info pair by blog id and user id.",
                    "httpMethod": "GET",
                    "id": "blogger.blogUserInfos.get",
                    "path": "v3/users/{userId}/blogs/{blogId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/blogger",
                        "https://www.googleapis.com/auth/blogger.readonly"
                    ]
                }
            }
        }
    },
    "revision": "20201006",
    "rootUrl": "https://blogger.googleapis.com/",
    "servicePath": "",
    "title": "Blogger API v3",
    "version": "v3"
}