{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/classroom.courses": {
                    "description": "Manage your Google Classroom classes"
                },
                "https://www.googleapis.com/auth/classroom.courses.readonly": {
                    "description": "View your Google Classroom classes"
                },
                "https://www.googleapis.com/auth/classroom.profile.emails": {
                    "description": "View the email addresses of people in your classes"
                },
                "https://www.googleapis.com/auth/classroom.profile.photos": {
                    "description": "View the profile photos of people in your classes"
                },
                "https://www.googleapis.com/auth/classroom.rosters": {
                    "description": "Manage your Google Classroom class rosters"
                },
                "https://www.googleapis.com/auth/classroom.rosters.readonly": {
                    "description": "View your Google Classroom class rosters"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://classroom.googleapis.com/",
    "batchPath": "batch",
    "description": "Google Classroom API",
    "discoveryVersion": "v1",
    "documentationLink": "",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/niuwoiUGTAQydy0rARLpR-dYbKw\"",
    "id": "classroom:v1",
    "kind": "discovery#restDescription",
    "name": "classroom",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "courses": {
            "methods": {
                "create": {
                    "description": "Creates a course. The user specified as the primary teacher in `primary_teacher_id` is the owner of the created course and added as a teacher. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses. * `NOT_FOUND` if the primary teacher is not a valid user. * `ALREADY_EXISTS` if an alias was specified and already exists.",
                    "httpMethod": "POST",
                    "id": "classroom.courses.create",
                    "path": "v1/courses",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "get": {
                    "description": "Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course. * `NOT_FOUND` if no course exists with the requested ID.",
                    "httpMethod": "GET",
                    "id": "classroom.courses.get",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses",
                        "https://www.googleapis.com/auth/classroom.courses.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course. * `NOT_FOUND` if no course exists with the requested ID.",
                    "httpMethod": "PUT",
                    "id": "classroom.courses.update",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "patch": {
                    "description": "Updates one or more fields a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied.",
                    "httpMethod": "PATCH",
                    "id": "classroom.courses.patch",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "delete": {
                    "description": "Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course. * `NOT_FOUND` if no course exists with the requested ID.",
                    "httpMethod": "DELETE",
                    "id": "classroom.courses.delete",
                    "path": "v1/courses/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses"
                    ]
                },
                "list": {
                    "description": "Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. This method returns the following error codes: * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.",
                    "httpMethod": "GET",
                    "id": "classroom.courses.list",
                    "path": "v1/courses",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.courses",
                        "https://www.googleapis.com/auth/classroom.courses.readonly"
                    ]
                }
            },
            "resources": {
                "aliases": {
                    "methods": {
                        "create": {
                            "description": "Creates an alias to a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the alias. * `NOT_FOUND` if the course does not exist. * `ALREADY_EXISTS` if the alias already exists.",
                            "httpMethod": "POST",
                            "id": "classroom.courses.aliases.create",
                            "path": "v1/courses/{courseId}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.courses"
                            ]
                        },
                        "delete": {
                            "description": "Deletes an alias of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to remove the alias. * `NOT_FOUND` if the alias does not exist.",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.aliases.delete",
                            "path": "v1/courses/{courseId}/aliases/{alias}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.courses"
                            ]
                        },
                        "list": {
                            "description": "Lists the aliases of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the course. * `NOT_FOUND` if the course does not exist.",
                            "httpMethod": "GET",
                            "id": "classroom.courses.aliases.list",
                            "path": "v1/courses/{courseId}/aliases",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.courses",
                                "https://www.googleapis.com/auth/classroom.courses.readonly"
                            ]
                        }
                    }
                },
                "teachers": {
                    "methods": {
                        "create": {
                            "description": "Creates a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create teachers in this course. * `NOT_FOUND` if the requested course ID does not exist. * `ALREADY_EXISTS` if the user is already a teacher or student in the course.",
                            "httpMethod": "POST",
                            "id": "classroom.courses.teachers.create",
                            "path": "v1/courses/{courseId}/teachers",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "get": {
                            "description": "Returns a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view teachers of this course. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist.",
                            "httpMethod": "GET",
                            "id": "classroom.courses.teachers.get",
                            "path": "v1/courses/{courseId}/teachers/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        },
                        "delete": {
                            "description": "Deletes a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete teachers of this course. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of this course.",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.teachers.delete",
                            "path": "v1/courses/{courseId}/teachers/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "list": {
                            "description": "Returns a list of teachers of this course that the requester is permitted to view. Fails with `NOT_FOUND` if the course does not exist.",
                            "httpMethod": "GET",
                            "id": "classroom.courses.teachers.list",
                            "path": "v1/courses/{courseId}/teachers",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        }
                    }
                },
                "students": {
                    "methods": {
                        "create": {
                            "description": "Adds a user as a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create students in this course. * `NOT_FOUND` if the requested course ID does not exist. * `ALREADY_EXISTS` if the user is already a student or student in the course.",
                            "httpMethod": "POST",
                            "id": "classroom.courses.students.create",
                            "path": "v1/courses/{courseId}/students",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "get": {
                            "description": "Returns a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view students of this course. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
                            "httpMethod": "GET",
                            "id": "classroom.courses.students.get",
                            "path": "v1/courses/{courseId}/students/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        },
                        "delete": {
                            "description": "Deletes a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete students of this course. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
                            "httpMethod": "DELETE",
                            "id": "classroom.courses.students.delete",
                            "path": "v1/courses/{courseId}/students/{userId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.rosters"
                            ]
                        },
                        "list": {
                            "description": "Returns a list of students of this course that the requester is permitted to view. Fails with `NOT_FOUND` if the course does not exist.",
                            "httpMethod": "GET",
                            "id": "classroom.courses.students.list",
                            "path": "v1/courses/{courseId}/students",
                            "scopes": [
                                "https://www.googleapis.com/auth/classroom.profile.emails",
                                "https://www.googleapis.com/auth/classroom.profile.photos",
                                "https://www.googleapis.com/auth/classroom.rosters",
                                "https://www.googleapis.com/auth/classroom.rosters.readonly"
                            ]
                        }
                    }
                }
            }
        },
        "invitations": {
            "methods": {
                "create": {
                    "description": "Creates a invitation. Only one invitation for a user and course may exist at a time. Delete and recreate an invitation to make changes. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create invitations for this course. * `NOT_FOUND` if the course or the user does not exist. * `ALREADY_EXISTS` if an invitation for the specified user and course already exists.",
                    "httpMethod": "POST",
                    "id": "classroom.invitations.create",
                    "path": "v1/invitations",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters"
                    ]
                },
                "get": {
                    "description": "Returns a invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view the requested invitation. * `NOT_FOUND` if no invitation exists with the requested ID.",
                    "httpMethod": "GET",
                    "id": "classroom.invitations.get",
                    "path": "v1/invitations/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters",
                        "https://www.googleapis.com/auth/classroom.rosters.readonly"
                    ]
                },
                "delete": {
                    "description": "Deletes a invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested invitation. * `NOT_FOUND` if no invitation exists with the requested ID.",
                    "httpMethod": "DELETE",
                    "id": "classroom.invitations.delete",
                    "path": "v1/invitations/{id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters"
                    ]
                },
                "list": {
                    "description": "Returns a list of invitations that the requesting user is permitted to view, restricted to those that match the request. *Note:* At least one of `user_id` or `course_id` must be supplied.",
                    "httpMethod": "GET",
                    "id": "classroom.invitations.list",
                    "path": "v1/invitations",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters",
                        "https://www.googleapis.com/auth/classroom.rosters.readonly"
                    ]
                },
                "accept": {
                    "description": "Accepts an invitation, removing it and adding the invited user to the teachers or students (as appropriate) of the specified course. Only the invited user may accept an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to accept the requested invitation. * `NOT_FOUND` if no invitation exists with the requested ID.",
                    "httpMethod": "POST",
                    "id": "classroom.invitations.accept",
                    "path": "v1/invitations/{id}:accept",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.rosters"
                    ]
                }
            }
        },
        "userProfiles": {
            "methods": {
                "get": {
                    "description": "Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile. * `NOT_FOUND` if the profile does not exist.",
                    "httpMethod": "GET",
                    "id": "classroom.userProfiles.get",
                    "path": "v1/userProfiles/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/classroom.profile.emails",
                        "https://www.googleapis.com/auth/classroom.profile.photos",
                        "https://www.googleapis.com/auth/classroom.rosters",
                        "https://www.googleapis.com/auth/classroom.rosters.readonly"
                    ]
                }
            }
        }
    },
    "revision": "20150628",
    "rootUrl": "https://classroom.googleapis.com/",
    "servicePath": "",
    "title": "Google Classroom API",
    "version": "v1"
}