{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/consumersurveys": {
                    "description": "View and edit your surveys and results"
                },
                "https://www.googleapis.com/auth/consumersurveys.readonly": {
                    "description": "View the results for your surveys"
                },
                "https://www.googleapis.com/auth/userinfo.email": {
                    "description": "View your email address"
                }
            }
        }
    },
    "basePath": "/consumersurveys/v2/",
    "baseUrl": "https://www.googleapis.com/consumersurveys/v2/",
    "batchPath": "batch",
    "description": "API for Google Consumer Surveys.",
    "discoveryVersion": "v1",
    "etag": "\"bRFOOrZKfO9LweMbPqu0kcu6De8/2ITXfTj3l8aU9YhKDrABM562udw\"",
    "id": "consumersurveys:v2",
    "kind": "discovery#restDescription",
    "name": "consumersurveys",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "results": {
            "methods": {
                "get": {
                    "description": "Retrieves any survey results that have been produced so far. Results are formatted as an Excel file.",
                    "httpMethod": "GET",
                    "id": "consumersurveys.results.get",
                    "path": "surveys/{surveyUrlId}/results",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/consumersurveys.readonly",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ],
                    "supportsMediaDownload": true
                }
            }
        },
        "surveys": {
            "methods": {
                "get": {
                    "description": "Retrieves information about the specified survey.",
                    "httpMethod": "GET",
                    "id": "consumersurveys.surveys.get",
                    "path": "surveys/{surveyUrlId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/consumersurveys.readonly",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                },
                "insert": {
                    "description": "Creates a survey.",
                    "httpMethod": "POST",
                    "id": "consumersurveys.surveys.insert",
                    "path": "surveys",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                },
                "list": {
                    "description": "Lists the surveys owned by the authenticated user.",
                    "httpMethod": "GET",
                    "id": "consumersurveys.surveys.list",
                    "path": "surveys",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/consumersurveys.readonly",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                },
                "start": {
                    "description": "Begins running a survey.",
                    "httpMethod": "POST",
                    "id": "consumersurveys.surveys.start",
                    "path": "surveys/{resourceId}/start",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                },
                "stop": {
                    "description": "Stops a running survey.",
                    "httpMethod": "POST",
                    "id": "consumersurveys.surveys.stop",
                    "path": "surveys/{resourceId}/stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                },
                "update": {
                    "description": "Updates a survey. Currently the only property that can be updated is the owners property.",
                    "httpMethod": "PUT",
                    "id": "consumersurveys.surveys.update",
                    "path": "surveys/{surveyUrlId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/consumersurveys",
                        "https://www.googleapis.com/auth/userinfo.email"
                    ]
                }
            }
        }
    },
    "revision": "20160405",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "consumersurveys/v2/",
    "title": "Consumer Surveys API",
    "version": "v2"
}