{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/coordinate": {
                    "description": "View and manage your Google Maps Coordinate jobs"
                },
                "https://www.googleapis.com/auth/coordinate.readonly": {
                    "description": "View your Google Coordinate jobs"
                }
            }
        }
    },
    "basePath": "/coordinate/v1/",
    "baseUrl": "https://www.googleapis.com/coordinate/v1/",
    "batchPath": "batch",
    "description": "Lets you view and manage jobs in a Coordinate team.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/coordinate/",
    "etag": "\"C5oy1hgQsABtYOYIOXWcR3BgYqU/MnvBWhcZU7xS2iIEoZ2wSIQNHiQ\"",
    "id": "coordinate:v1",
    "kind": "discovery#restDescription",
    "name": "coordinate",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "customFieldDef": {
            "methods": {
                "list": {
                    "description": "Retrieves a list of custom field definitions for a team.",
                    "httpMethod": "GET",
                    "id": "coordinate.customFieldDef.list",
                    "path": "teams/{teamId}/custom_fields",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                }
            }
        },
        "jobs": {
            "methods": {
                "get": {
                    "description": "Retrieves a job, including all the changes made to the job.",
                    "httpMethod": "GET",
                    "id": "coordinate.jobs.get",
                    "path": "teams/{teamId}/jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                },
                "insert": {
                    "description": "Inserts a new job. Only the state field of the job should be set.",
                    "httpMethod": "POST",
                    "id": "coordinate.jobs.insert",
                    "path": "teams/{teamId}/jobs",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate"
                    ]
                },
                "list": {
                    "description": "Retrieves jobs created or modified since the given timestamp.",
                    "httpMethod": "GET",
                    "id": "coordinate.jobs.list",
                    "path": "teams/{teamId}/jobs",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a job. Fields that are set in the job state will be updated. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "coordinate.jobs.patch",
                    "path": "teams/{teamId}/jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate"
                    ]
                },
                "update": {
                    "description": "Updates a job. Fields that are set in the job state will be updated.",
                    "httpMethod": "PUT",
                    "id": "coordinate.jobs.update",
                    "path": "teams/{teamId}/jobs/{jobId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate"
                    ]
                }
            }
        },
        "location": {
            "methods": {
                "list": {
                    "description": "Retrieves a list of locations for a worker.",
                    "httpMethod": "GET",
                    "id": "coordinate.location.list",
                    "path": "teams/{teamId}/workers/{workerEmail}/locations",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                }
            }
        },
        "schedule": {
            "methods": {
                "get": {
                    "description": "Retrieves the schedule for a job.",
                    "httpMethod": "GET",
                    "id": "coordinate.schedule.get",
                    "path": "teams/{teamId}/jobs/{jobId}/schedule",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                },
                "patch": {
                    "description": "Replaces the schedule of a job with the provided schedule. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "coordinate.schedule.patch",
                    "path": "teams/{teamId}/jobs/{jobId}/schedule",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate"
                    ]
                },
                "update": {
                    "description": "Replaces the schedule of a job with the provided schedule.",
                    "httpMethod": "PUT",
                    "id": "coordinate.schedule.update",
                    "path": "teams/{teamId}/jobs/{jobId}/schedule",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate"
                    ]
                }
            }
        },
        "team": {
            "methods": {
                "list": {
                    "description": "Retrieves a list of teams for a user.",
                    "httpMethod": "GET",
                    "id": "coordinate.team.list",
                    "path": "teams",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                }
            }
        },
        "worker": {
            "methods": {
                "list": {
                    "description": "Retrieves a list of workers in a team.",
                    "httpMethod": "GET",
                    "id": "coordinate.worker.list",
                    "path": "teams/{teamId}/workers",
                    "scopes": [
                        "https://www.googleapis.com/auth/coordinate",
                        "https://www.googleapis.com/auth/coordinate.readonly"
                    ]
                }
            }
        }
    },
    "revision": "20150811",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "coordinate/v1/",
    "title": "Google Maps Coordinate API",
    "version": "v1"
}