{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive": {
                    "description": "View and manage the files in your Google Drive"
                },
                "https://www.googleapis.com/auth/drive.appdata": {
                    "description": "View and manage its own configuration data in your Google Drive"
                },
                "https://www.googleapis.com/auth/drive.apps.readonly": {
                    "description": "View your Google Drive apps"
                },
                "https://www.googleapis.com/auth/drive.file": {
                    "description": "View and manage Google Drive files and folders that you have opened or created with this app"
                },
                "https://www.googleapis.com/auth/drive.metadata": {
                    "description": "View and manage metadata of files in your Google Drive"
                },
                "https://www.googleapis.com/auth/drive.metadata.readonly": {
                    "description": "View metadata for files in your Google Drive"
                },
                "https://www.googleapis.com/auth/drive.photos.readonly": {
                    "description": "View the photos, videos and albums in your Google Photos"
                },
                "https://www.googleapis.com/auth/drive.readonly": {
                    "description": "View the files in your Google Drive"
                },
                "https://www.googleapis.com/auth/drive.scripts": {
                    "description": "Modify your Google Apps Script scripts' behavior"
                }
            }
        }
    },
    "basePath": "/drive/v2/",
    "baseUrl": "https://www.googleapis.com/drive/v2/",
    "batchPath": "batch",
    "description": "The API to interact with Drive.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/drive/",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/plQwzVIDWGtIGduRkjd1Yo9v3ps\"",
    "id": "drive:v2",
    "kind": "discovery#restDescription",
    "name": "drive",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "about": {
            "methods": {
                "get": {
                    "description": "Gets the information about the current user along with Drive API settings",
                    "httpMethod": "GET",
                    "id": "drive.about.get",
                    "path": "about",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "apps": {
            "methods": {
                "get": {
                    "description": "Gets a specific app.",
                    "httpMethod": "GET",
                    "id": "drive.apps.get",
                    "path": "apps/{appId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "description": "Lists a user's installed apps.",
                    "httpMethod": "GET",
                    "id": "drive.apps.list",
                    "path": "apps",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.apps.readonly"
                    ]
                }
            }
        },
        "changes": {
            "methods": {
                "get": {
                    "description": "Gets a specific change.",
                    "httpMethod": "GET",
                    "id": "drive.changes.get",
                    "path": "changes/{changeId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "description": "Lists the changes for a user.",
                    "httpMethod": "GET",
                    "id": "drive.changes.list",
                    "path": "changes",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsSubscription": true
                },
                "watch": {
                    "description": "Subscribe to changes for a user.",
                    "httpMethod": "POST",
                    "id": "drive.changes.watch",
                    "path": "changes/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsSubscription": true
                }
            }
        },
        "channels": {
            "methods": {
                "stop": {
                    "description": "Stop watching resources through this channel",
                    "httpMethod": "POST",
                    "id": "drive.channels.stop",
                    "path": "channels/stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "children": {
            "methods": {
                "delete": {
                    "description": "Removes a child from a folder.",
                    "httpMethod": "DELETE",
                    "id": "drive.children.delete",
                    "path": "files/{folderId}/children/{childId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a specific child reference.",
                    "httpMethod": "GET",
                    "id": "drive.children.get",
                    "path": "files/{folderId}/children/{childId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Inserts a file into a folder.",
                    "httpMethod": "POST",
                    "id": "drive.children.insert",
                    "path": "files/{folderId}/children",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "list": {
                    "description": "Lists a folder's children.",
                    "httpMethod": "GET",
                    "id": "drive.children.list",
                    "path": "files/{folderId}/children",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "delete": {
                    "description": "Deletes a comment.",
                    "httpMethod": "DELETE",
                    "id": "drive.comments.delete",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a comment by ID.",
                    "httpMethod": "GET",
                    "id": "drive.comments.get",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates a new comment on the given file.",
                    "httpMethod": "POST",
                    "id": "drive.comments.insert",
                    "path": "files/{fileId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "list": {
                    "description": "Lists a file's comments.",
                    "httpMethod": "GET",
                    "id": "drive.comments.list",
                    "path": "files/{fileId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates an existing comment. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "drive.comments.patch",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "update": {
                    "description": "Updates an existing comment.",
                    "httpMethod": "PUT",
                    "id": "drive.comments.update",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "files": {
            "methods": {
                "copy": {
                    "description": "Creates a copy of the specified file.",
                    "httpMethod": "POST",
                    "id": "drive.files.copy",
                    "path": "files/{fileId}/copy",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.photos.readonly"
                    ]
                },
                "delete": {
                    "description": "Permanently deletes a file by ID. Skips the trash. The currently authenticated user must own the file.",
                    "httpMethod": "DELETE",
                    "id": "drive.files.delete",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "emptyTrash": {
                    "description": "Permanently deletes all of the user's trashed files.",
                    "httpMethod": "DELETE",
                    "id": "drive.files.emptyTrash",
                    "path": "files/trash",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "generateIds": {
                    "description": "Generates a set of file IDs which can be provided in insert requests.",
                    "httpMethod": "GET",
                    "id": "drive.files.generateIds",
                    "path": "files/generateIds",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a file's metadata by ID.",
                    "httpMethod": "GET",
                    "id": "drive.files.get",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true,
                    "supportsSubscription": true
                },
                "insert": {
                    "description": "Insert a new file.",
                    "httpMethod": "POST",
                    "id": "drive.files.insert",
                    "path": "files",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "supportsMediaUpload": true,
                    "supportsSubscription": true
                },
                "list": {
                    "description": "Lists the user's files.",
                    "httpMethod": "GET",
                    "id": "drive.files.list",
                    "path": "files",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates file metadata and/or content. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "drive.files.patch",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ]
                },
                "touch": {
                    "description": "Set the file's updated time to the current server time.",
                    "httpMethod": "POST",
                    "id": "drive.files.touch",
                    "path": "files/{fileId}/touch",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                },
                "trash": {
                    "description": "Moves a file to the trash. The currently authenticated user must own the file.",
                    "httpMethod": "POST",
                    "id": "drive.files.trash",
                    "path": "files/{fileId}/trash",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "untrash": {
                    "description": "Restores a file from the trash.",
                    "httpMethod": "POST",
                    "id": "drive.files.untrash",
                    "path": "files/{fileId}/untrash",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "update": {
                    "description": "Updates file metadata and/or content.",
                    "httpMethod": "PUT",
                    "id": "drive.files.update",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ],
                    "supportsMediaUpload": true
                },
                "watch": {
                    "description": "Subscribe to changes on a file",
                    "httpMethod": "POST",
                    "id": "drive.files.watch",
                    "path": "files/{fileId}/watch",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true,
                    "supportsSubscription": true
                }
            }
        },
        "parents": {
            "methods": {
                "delete": {
                    "description": "Removes a parent from a file.",
                    "httpMethod": "DELETE",
                    "id": "drive.parents.delete",
                    "path": "files/{fileId}/parents/{parentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a specific parent reference.",
                    "httpMethod": "GET",
                    "id": "drive.parents.get",
                    "path": "files/{fileId}/parents/{parentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Adds a parent folder for a file.",
                    "httpMethod": "POST",
                    "id": "drive.parents.insert",
                    "path": "files/{fileId}/parents",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "list": {
                    "description": "Lists a file's parents.",
                    "httpMethod": "GET",
                    "id": "drive.parents.list",
                    "path": "files/{fileId}/parents",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "permissions": {
            "methods": {
                "delete": {
                    "description": "Deletes a permission from a file.",
                    "httpMethod": "DELETE",
                    "id": "drive.permissions.delete",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a permission by ID.",
                    "httpMethod": "GET",
                    "id": "drive.permissions.get",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "getIdForEmail": {
                    "description": "Returns the permission ID for an email address.",
                    "httpMethod": "GET",
                    "id": "drive.permissions.getIdForEmail",
                    "path": "permissionIds/{email}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Inserts a permission for a file.",
                    "httpMethod": "POST",
                    "id": "drive.permissions.insert",
                    "path": "files/{fileId}/permissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "list": {
                    "description": "Lists a file's permissions.",
                    "httpMethod": "GET",
                    "id": "drive.permissions.list",
                    "path": "files/{fileId}/permissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a permission. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "drive.permissions.patch",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "update": {
                    "description": "Updates a permission.",
                    "httpMethod": "PUT",
                    "id": "drive.permissions.update",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "properties": {
            "methods": {
                "delete": {
                    "description": "Deletes a property.",
                    "httpMethod": "DELETE",
                    "id": "drive.properties.delete",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                },
                "get": {
                    "description": "Gets a property by its key.",
                    "httpMethod": "GET",
                    "id": "drive.properties.get",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Adds a property to a file.",
                    "httpMethod": "POST",
                    "id": "drive.properties.insert",
                    "path": "files/{fileId}/properties",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                },
                "list": {
                    "description": "Lists a file's properties.",
                    "httpMethod": "GET",
                    "id": "drive.properties.list",
                    "path": "files/{fileId}/properties",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a property. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "drive.properties.patch",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                },
                "update": {
                    "description": "Updates a property.",
                    "httpMethod": "PUT",
                    "id": "drive.properties.update",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                }
            }
        },
        "realtime": {
            "methods": {
                "get": {
                    "description": "Exports the contents of the Realtime API data model associated with this file as JSON.",
                    "httpMethod": "GET",
                    "id": "drive.realtime.get",
                    "path": "files/{fileId}/realtime",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "supportsMediaDownload": true
                },
                "update": {
                    "description": "Overwrites the Realtime API data model associated with this file with the provided JSON data model.",
                    "httpMethod": "PUT",
                    "id": "drive.realtime.update",
                    "path": "files/{fileId}/realtime",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "supportsMediaUpload": true
                }
            }
        },
        "replies": {
            "methods": {
                "delete": {
                    "description": "Deletes a reply.",
                    "httpMethod": "DELETE",
                    "id": "drive.replies.delete",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a reply.",
                    "httpMethod": "GET",
                    "id": "drive.replies.get",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates a new reply to the given comment.",
                    "httpMethod": "POST",
                    "id": "drive.replies.insert",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "list": {
                    "description": "Lists all of the replies to a comment.",
                    "httpMethod": "GET",
                    "id": "drive.replies.list",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates an existing reply. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "drive.replies.patch",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "update": {
                    "description": "Updates an existing reply.",
                    "httpMethod": "PUT",
                    "id": "drive.replies.update",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        },
        "revisions": {
            "methods": {
                "delete": {
                    "description": "Removes a revision.",
                    "httpMethod": "DELETE",
                    "id": "drive.revisions.delete",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "description": "Gets a specific revision.",
                    "httpMethod": "GET",
                    "id": "drive.revisions.get",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "list": {
                    "description": "Lists a file's revisions.",
                    "httpMethod": "GET",
                    "id": "drive.revisions.list",
                    "path": "files/{fileId}/revisions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a revision. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "drive.revisions.patch",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "update": {
                    "description": "Updates a revision.",
                    "httpMethod": "PUT",
                    "id": "drive.revisions.update",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                }
            }
        }
    },
    "revision": "20150806",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "drive/v2/",
    "title": "Drive API",
    "version": "v2"
}