{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://mail.google.com/": {
                    "description": "View and manage your mail"
                },
                "https://www.googleapis.com/auth/gmail.compose": {
                    "description": "Manage drafts and send emails"
                },
                "https://www.googleapis.com/auth/gmail.insert": {
                    "description": "Insert mail into your mailbox"
                },
                "https://www.googleapis.com/auth/gmail.labels": {
                    "description": "Manage mailbox labels"
                },
                "https://www.googleapis.com/auth/gmail.modify": {
                    "description": "View and modify but not delete your email"
                },
                "https://www.googleapis.com/auth/gmail.readonly": {
                    "description": "View your emails messages and settings"
                },
                "https://www.googleapis.com/auth/gmail.send": {
                    "description": "Send email on your behalf"
                }
            }
        }
    },
    "basePath": "/gmail/v1/users/",
    "baseUrl": "https://www.googleapis.com/gmail/v1/users/",
    "batchPath": "batch",
    "description": "The Gmail REST API.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/gmail/api/",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/epKZlPw-j_GuhHfSnsAczxcvTBU\"",
    "id": "gmail:v1",
    "kind": "discovery#restDescription",
    "name": "gmail",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "users": {
            "methods": {
                "getProfile": {
                    "description": "Gets the current user's Gmail profile.",
                    "httpMethod": "GET",
                    "id": "gmail.users.getProfile",
                    "path": "{userId}/profile",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.compose",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly"
                    ]
                },
                "stop": {
                    "description": "Stop receiving push notifications for the given user mailbox.",
                    "httpMethod": "POST",
                    "id": "gmail.users.stop",
                    "path": "{userId}/stop",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly"
                    ]
                },
                "watch": {
                    "description": "Set up or update a push notification watch on the given user mailbox.",
                    "httpMethod": "POST",
                    "id": "gmail.users.watch",
                    "path": "{userId}/watch",
                    "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly"
                    ]
                }
            },
            "resources": {
                "drafts": {
                    "methods": {
                        "create": {
                            "description": "Creates a new draft with the DRAFT label.",
                            "httpMethod": "POST",
                            "id": "gmail.users.drafts.create",
                            "path": "{userId}/drafts",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "delete": {
                            "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.drafts.delete",
                            "path": "{userId}/drafts/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "get": {
                            "description": "Gets the specified draft.",
                            "httpMethod": "GET",
                            "id": "gmail.users.drafts.get",
                            "path": "{userId}/drafts/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "list": {
                            "description": "Lists the drafts in the user's mailbox.",
                            "httpMethod": "GET",
                            "id": "gmail.users.drafts.list",
                            "path": "{userId}/drafts",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "send": {
                            "description": "Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers.",
                            "httpMethod": "POST",
                            "id": "gmail.users.drafts.send",
                            "path": "{userId}/drafts/send",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "update": {
                            "description": "Replaces a draft's content.",
                            "httpMethod": "PUT",
                            "id": "gmail.users.drafts.update",
                            "path": "{userId}/drafts/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        }
                    }
                },
                "history": {
                    "methods": {
                        "list": {
                            "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing historyId).",
                            "httpMethod": "GET",
                            "id": "gmail.users.history.list",
                            "path": "{userId}/history",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        }
                    }
                },
                "labels": {
                    "methods": {
                        "create": {
                            "description": "Creates a new label.",
                            "httpMethod": "POST",
                            "id": "gmail.users.labels.create",
                            "path": "{userId}/labels",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "delete": {
                            "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.labels.delete",
                            "path": "{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "get": {
                            "description": "Gets the specified label.",
                            "httpMethod": "GET",
                            "id": "gmail.users.labels.get",
                            "path": "{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "list": {
                            "description": "Lists all labels in the user's mailbox.",
                            "httpMethod": "GET",
                            "id": "gmail.users.labels.list",
                            "path": "{userId}/labels",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "patch": {
                            "description": "Updates the specified label. This method supports patch semantics.",
                            "httpMethod": "PATCH",
                            "id": "gmail.users.labels.patch",
                            "path": "{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "update": {
                            "description": "Updates the specified label.",
                            "httpMethod": "PUT",
                            "id": "gmail.users.labels.update",
                            "path": "{userId}/labels/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.labels",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        }
                    }
                },
                "messages": {
                    "methods": {
                        "delete": {
                            "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer messages.trash instead.",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.messages.delete",
                            "path": "{userId}/messages/{id}",
                            "scopes": [
                                "https://mail.google.com/"
                            ]
                        },
                        "get": {
                            "description": "Gets the specified message.",
                            "httpMethod": "GET",
                            "id": "gmail.users.messages.get",
                            "path": "{userId}/messages/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "import": {
                            "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message.",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.import",
                            "path": "{userId}/messages/import",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.insert",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "insert": {
                            "description": "Directly inserts a message into only this user's mailbox similar to IMAP APPEND, bypassing most scanning and classification. Does not send a message.",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.insert",
                            "path": "{userId}/messages",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.insert",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ],
                            "supportsMediaUpload": true
                        },
                        "list": {
                            "description": "Lists the messages in the user's mailbox.",
                            "httpMethod": "GET",
                            "id": "gmail.users.messages.list",
                            "path": "{userId}/messages",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "modify": {
                            "description": "Modifies the labels on the specified message.",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.modify",
                            "path": "{userId}/messages/{id}/modify",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "send": {
                            "description": "Sends the specified message to the recipients in the To, Cc, and Bcc headers.",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.send",
                            "path": "{userId}/messages/send",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.compose",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.send"
                            ],
                            "supportsMediaUpload": true
                        },
                        "trash": {
                            "description": "Moves the specified message to the trash.",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.trash",
                            "path": "{userId}/messages/{id}/trash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "untrash": {
                            "description": "Removes the specified message from the trash.",
                            "httpMethod": "POST",
                            "id": "gmail.users.messages.untrash",
                            "path": "{userId}/messages/{id}/untrash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        }
                    },
                    "resources": {
                        "attachments": {
                            "methods": {
                                "get": {
                                    "description": "Gets the specified message attachment.",
                                    "httpMethod": "GET",
                                    "id": "gmail.users.messages.attachments.get",
                                    "path": "{userId}/messages/{messageId}/attachments/{id}",
                                    "scopes": [
                                        "https://mail.google.com/",
                                        "https://www.googleapis.com/auth/gmail.modify",
                                        "https://www.googleapis.com/auth/gmail.readonly"
                                    ]
                                }
                            }
                        }
                    }
                },
                "threads": {
                    "methods": {
                        "delete": {
                            "description": "Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.",
                            "httpMethod": "DELETE",
                            "id": "gmail.users.threads.delete",
                            "path": "{userId}/threads/{id}",
                            "scopes": [
                                "https://mail.google.com/"
                            ]
                        },
                        "get": {
                            "description": "Gets the specified thread.",
                            "httpMethod": "GET",
                            "id": "gmail.users.threads.get",
                            "path": "{userId}/threads/{id}",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "list": {
                            "description": "Lists the threads in the user's mailbox.",
                            "httpMethod": "GET",
                            "id": "gmail.users.threads.list",
                            "path": "{userId}/threads",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify",
                                "https://www.googleapis.com/auth/gmail.readonly"
                            ]
                        },
                        "modify": {
                            "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
                            "httpMethod": "POST",
                            "id": "gmail.users.threads.modify",
                            "path": "{userId}/threads/{id}/modify",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "trash": {
                            "description": "Moves the specified thread to the trash.",
                            "httpMethod": "POST",
                            "id": "gmail.users.threads.trash",
                            "path": "{userId}/threads/{id}/trash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        },
                        "untrash": {
                            "description": "Removes the specified thread from the trash.",
                            "httpMethod": "POST",
                            "id": "gmail.users.threads.untrash",
                            "path": "{userId}/threads/{id}/untrash",
                            "scopes": [
                                "https://mail.google.com/",
                                "https://www.googleapis.com/auth/gmail.modify"
                            ]
                        }
                    }
                }
            }
        }
    },
    "revision": "20150910",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "gmail/v1/users/",
    "title": "Gmail API",
    "version": "v1"
}