{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/orkut": {
                    "description": "Manage your Orkut activity"
                },
                "https://www.googleapis.com/auth/orkut.readonly": {
                    "description": "View your Orkut data"
                }
            }
        }
    },
    "basePath": "/orkut/v2/",
    "baseUrl": "https://www.googleapis.com/orkut/v2/",
    "batchPath": "batch",
    "description": "Lets you manage activities, comments and badges in Orkut. More stuff coming in time.",
    "discoveryVersion": "v1",
    "documentationLink": "http://code.google.com/apis/orkut/v2/reference.html",
    "etag": "\"uUWyYHXmEn-ab7WLvo8qNz2S8ws/qCYcIF9SU9Hl8Qg-et4yd-nbiwI\"",
    "id": "orkut:v2",
    "kind": "discovery#restDescription",
    "name": "orkut",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "acl": {
            "methods": {
                "delete": {
                    "description": "Excludes an element from the ACL of the activity.",
                    "httpMethod": "DELETE",
                    "id": "orkut.acl.delete",
                    "path": "activities/{activityId}/acl/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                }
            }
        },
        "activities": {
            "methods": {
                "delete": {
                    "description": "Deletes an existing activity, if the access controls allow it.",
                    "httpMethod": "DELETE",
                    "id": "orkut.activities.delete",
                    "path": "activities/{activityId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "list": {
                    "description": "Retrieves a list of activities.",
                    "httpMethod": "GET",
                    "id": "orkut.activities.list",
                    "path": "people/{userId}/activities/{collection}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "activityVisibility": {
            "methods": {
                "get": {
                    "description": "Gets the visibility of an existing activity.",
                    "httpMethod": "GET",
                    "id": "orkut.activityVisibility.get",
                    "path": "activities/{activityId}/visibility",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates the visibility of an existing activity. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "orkut.activityVisibility.patch",
                    "path": "activities/{activityId}/visibility",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "update": {
                    "description": "Updates the visibility of an existing activity.",
                    "httpMethod": "PUT",
                    "id": "orkut.activityVisibility.update",
                    "path": "activities/{activityId}/visibility",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                }
            }
        },
        "badges": {
            "methods": {
                "get": {
                    "description": "Retrieves a badge from a user.",
                    "httpMethod": "GET",
                    "id": "orkut.badges.get",
                    "path": "people/{userId}/badges/{badgeId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieves the list of visible badges of a user.",
                    "httpMethod": "GET",
                    "id": "orkut.badges.list",
                    "path": "people/{userId}/badges",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "delete": {
                    "description": "Deletes an existing comment.",
                    "httpMethod": "DELETE",
                    "id": "orkut.comments.delete",
                    "path": "comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "get": {
                    "description": "Retrieves an existing comment.",
                    "httpMethod": "GET",
                    "id": "orkut.comments.get",
                    "path": "comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "insert": {
                    "description": "Inserts a new comment to an activity.",
                    "httpMethod": "POST",
                    "id": "orkut.comments.insert",
                    "path": "activities/{activityId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "list": {
                    "description": "Retrieves a list of comments, possibly filtered.",
                    "httpMethod": "GET",
                    "id": "orkut.comments.list",
                    "path": "activities/{activityId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communities": {
            "methods": {
                "get": {
                    "description": "Retrieves the basic information (aka. profile) of a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communities.get",
                    "path": "communities/{communityId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieves the list of communities the current user is a member of.",
                    "httpMethod": "GET",
                    "id": "orkut.communities.list",
                    "path": "people/{userId}/communities",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communityFollow": {
            "methods": {
                "delete": {
                    "description": "Removes a user from the followers of a community.",
                    "httpMethod": "DELETE",
                    "id": "orkut.communityFollow.delete",
                    "path": "communities/{communityId}/followers/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "insert": {
                    "description": "Adds a user as a follower of a community.",
                    "httpMethod": "POST",
                    "id": "orkut.communityFollow.insert",
                    "path": "communities/{communityId}/followers/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                }
            }
        },
        "communityMembers": {
            "methods": {
                "delete": {
                    "description": "Makes the user leave a community.",
                    "httpMethod": "DELETE",
                    "id": "orkut.communityMembers.delete",
                    "path": "communities/{communityId}/members/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "get": {
                    "description": "Retrieves the relationship between a user and a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communityMembers.get",
                    "path": "communities/{communityId}/members/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "insert": {
                    "description": "Makes the user join a community.",
                    "httpMethod": "POST",
                    "id": "orkut.communityMembers.insert",
                    "path": "communities/{communityId}/members/{userId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "list": {
                    "description": "Lists members of a community. Use the pagination tokens to retrieve the full list; do not rely on the member count available in the community profile information to know when to stop iterating, as that count may be approximate.",
                    "httpMethod": "GET",
                    "id": "orkut.communityMembers.list",
                    "path": "communities/{communityId}/members",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communityMessages": {
            "methods": {
                "delete": {
                    "description": "Moves a message of the community to the trash folder.",
                    "httpMethod": "DELETE",
                    "id": "orkut.communityMessages.delete",
                    "path": "communities/{communityId}/topics/{topicId}/messages/{messageId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "insert": {
                    "description": "Adds a message to a given community topic.",
                    "httpMethod": "POST",
                    "id": "orkut.communityMessages.insert",
                    "path": "communities/{communityId}/topics/{topicId}/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "list": {
                    "description": "Retrieves the messages of a topic of a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communityMessages.list",
                    "path": "communities/{communityId}/topics/{topicId}/messages",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communityPollComments": {
            "methods": {
                "insert": {
                    "description": "Adds a comment on a community poll.",
                    "httpMethod": "POST",
                    "id": "orkut.communityPollComments.insert",
                    "path": "communities/{communityId}/polls/{pollId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "list": {
                    "description": "Retrieves the comments of a community poll.",
                    "httpMethod": "GET",
                    "id": "orkut.communityPollComments.list",
                    "path": "communities/{communityId}/polls/{pollId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communityPollVotes": {
            "methods": {
                "insert": {
                    "description": "Votes on a community poll.",
                    "httpMethod": "POST",
                    "id": "orkut.communityPollVotes.insert",
                    "path": "communities/{communityId}/polls/{pollId}/votes",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                }
            }
        },
        "communityPolls": {
            "methods": {
                "get": {
                    "description": "Retrieves one specific poll of a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communityPolls.get",
                    "path": "communities/{communityId}/polls/{pollId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "list": {
                    "description": "Retrieves the polls of a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communityPolls.list",
                    "path": "communities/{communityId}/polls",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communityRelated": {
            "methods": {
                "list": {
                    "description": "Retrieves the communities related to another one.",
                    "httpMethod": "GET",
                    "id": "orkut.communityRelated.list",
                    "path": "communities/{communityId}/related",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "communityTopics": {
            "methods": {
                "delete": {
                    "description": "Moves a topic of the community to the trash folder.",
                    "httpMethod": "DELETE",
                    "id": "orkut.communityTopics.delete",
                    "path": "communities/{communityId}/topics/{topicId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "get": {
                    "description": "Retrieves a topic of a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communityTopics.get",
                    "path": "communities/{communityId}/topics/{topicId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                },
                "insert": {
                    "description": "Adds a topic to a given community.",
                    "httpMethod": "POST",
                    "id": "orkut.communityTopics.insert",
                    "path": "communities/{communityId}/topics",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                },
                "list": {
                    "description": "Retrieves the topics of a community.",
                    "httpMethod": "GET",
                    "id": "orkut.communityTopics.list",
                    "path": "communities/{communityId}/topics",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "counters": {
            "methods": {
                "list": {
                    "description": "Retrieves the counters of a user.",
                    "httpMethod": "GET",
                    "id": "orkut.counters.list",
                    "path": "people/{userId}/counters",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut",
                        "https://www.googleapis.com/auth/orkut.readonly"
                    ]
                }
            }
        },
        "scraps": {
            "methods": {
                "insert": {
                    "description": "Creates a new scrap.",
                    "httpMethod": "POST",
                    "id": "orkut.scraps.insert",
                    "path": "activities/scraps",
                    "scopes": [
                        "https://www.googleapis.com/auth/orkut"
                    ]
                }
            }
        }
    },
    "revision": "20120223",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "orkut/v2/",
    "title": "Orkut API",
    "version": "v2"
}