{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/contacts": {
                    "description": "Manage your contacts"
                },
                "https://www.googleapis.com/auth/contacts.readonly": {
                    "description": "View your contacts"
                },
                "https://www.googleapis.com/auth/plus.login": {
                    "description": "Know your basic profile info and list of people in your circles."
                },
                "https://www.googleapis.com/auth/user.addresses.read": {
                    "description": "View your street addresses"
                },
                "https://www.googleapis.com/auth/user.birthday.read": {
                    "description": "View your complete date of birth"
                },
                "https://www.googleapis.com/auth/user.emails.read": {
                    "description": "View your email addresses"
                },
                "https://www.googleapis.com/auth/user.phonenumbers.read": {
                    "description": "View your phone numbers"
                },
                "https://www.googleapis.com/auth/userinfo.email": {
                    "description": "View your email address"
                },
                "https://www.googleapis.com/auth/userinfo.profile": {
                    "description": "View your basic profile info"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://people.googleapis.com/",
    "batchPath": "batch",
    "description": "The Google People API service gives access to information about profiles and contacts.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/people/",
    "etag": "\"bRFOOrZKfO9LweMbPqu0kcu6De8/tzwJjoO4XDFgwNQjmiM8lPsFMzA\"",
    "id": "people:v1",
    "kind": "discovery#restDescription",
    "name": "people",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "people": {
            "methods": {
                "get": {
                    "description": "Provides information about a person resource for a resource name. Use `people/me` to indicate the authenticated user.",
                    "httpMethod": "GET",
                    "id": "people.people.get",
                    "path": "v1/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/plus.login",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ]
                },
                "getBatchGet": {
                    "description": "Provides information about a list of specific people by specifying a list of requested resource names. Use `people/me` to indicate the authenticated user.",
                    "httpMethod": "GET",
                    "id": "people.people.getBatchGet",
                    "path": "v1/people:batchGet",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/plus.login",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ]
                }
            },
            "resources": {
                "connections": {
                    "methods": {
                        "list": {
                            "description": "Provides a list of the authenticated user's contacts merged with any linked profiles.",
                            "httpMethod": "GET",
                            "id": "people.people.connections.list",
                            "path": "v1/{+resourceName}/connections",
                            "scopes": [
                                "https://www.googleapis.com/auth/contacts",
                                "https://www.googleapis.com/auth/contacts.readonly"
                            ]
                        }
                    }
                }
            }
        }
    },
    "revision": "20160210",
    "rootUrl": "https://people.googleapis.com/",
    "servicePath": "",
    "title": "Google People API",
    "version": "v1"
}