{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/plus.login": {
                    "description": "Know the list of people in your circles, your age range, and language"
                },
                "https://www.googleapis.com/auth/userinfo.profile": {
                    "description": "View your basic profile info"
                },
                "https://www.googleapis.com/auth/user.emails.read": {
                    "description": "View your email addresses"
                },
                "https://www.googleapis.com/auth/contacts": {
                    "description": "Manage your contacts"
                },
                "https://www.googleapis.com/auth/user.addresses.read": {
                    "description": "View your street addresses"
                },
                "https://www.googleapis.com/auth/user.phonenumbers.read": {
                    "description": "View your phone numbers"
                },
                "https://www.googleapis.com/auth/userinfo.email": {
                    "description": "View your email address"
                },
                "https://www.googleapis.com/auth/user.birthday.read": {
                    "description": "View your complete date of birth"
                },
                "https://www.googleapis.com/auth/contacts.readonly": {
                    "description": "View your contacts"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://people.googleapis.com/",
    "batchPath": "batch",
    "description": "Provides access to information about profiles and contacts.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/people/",
    "id": "people:v1",
    "kind": "discovery#restDescription",
    "name": "people",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "people": {
            "methods": {
                "getBatchGet": {
                    "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.",
                    "httpMethod": "GET",
                    "id": "people.people.getBatchGet",
                    "path": "v1/people:batchGet",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/plus.login",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ]
                },
                "get": {
                    "description": "Provides information about a person resource for a resource name. Use\n`people/me` to indicate the authenticated user.",
                    "httpMethod": "GET",
                    "id": "people.people.get",
                    "path": "v1/{+resourceName}",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/plus.login",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ]
                }
            },
            "resources": {
                "me": {
                    "resources": {
                        "connections": {
                            "methods": {
                                "list": {
                                    "description": "Provides a list of the authenticated user's contacts merged with any\nlinked profiles.",
                                    "httpMethod": "GET",
                                    "id": "people.people.me.connections.list",
                                    "path": "v1/people/me/connections",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/contacts",
                                        "https://www.googleapis.com/auth/contacts.readonly"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "revision": "20170209",
    "rootUrl": "https://people.googleapis.com/",
    "servicePath": "",
    "title": "Google People API",
    "version": "v1"
}