{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/apps.order": {
                    "description": "Manage users on your domain"
                },
                "https://www.googleapis.com/auth/apps.order.readonly": {
                    "description": "Manage users on your domain"
                }
            }
        }
    },
    "basePath": "/apps/reseller/v1sandbox/",
    "baseUrl": "https://www.googleapis.com/apps/reseller/v1sandbox/",
    "batchPath": "batch",
    "description": "Lets you create and manage your customers and their subscriptions.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/google-apps/reseller/",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/6n7xpEQ8zC7k2Rxf1zW5XjwY8yg\"",
    "id": "reseller:v1sandbox",
    "kind": "discovery#restDescription",
    "labels": [
        "limited_availability"
    ],
    "name": "reseller",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "customers": {
            "methods": {
                "get": {
                    "description": "Gets a customer resource if one exists and is owned by the reseller.",
                    "httpMethod": "GET",
                    "id": "reseller.customers.get",
                    "path": "customers/{customerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates a customer resource if one does not already exist.",
                    "httpMethod": "POST",
                    "id": "reseller.customers.insert",
                    "path": "customers",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "patch": {
                    "description": "Update a customer resource if one it exists and is owned by the reseller. This method supports patch semantics.",
                    "httpMethod": "PATCH",
                    "id": "reseller.customers.patch",
                    "path": "customers/{customerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "update": {
                    "description": "Update a customer resource if one it exists and is owned by the reseller.",
                    "httpMethod": "PUT",
                    "id": "reseller.customers.update",
                    "path": "customers/{customerId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                }
            }
        },
        "subscriptions": {
            "methods": {
                "activate": {
                    "description": "Activates a subscription previously suspended by the reseller",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.activate",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/activate",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "changePlan": {
                    "description": "Changes the plan of a subscription",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.changePlan",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "changeRenewalSettings": {
                    "description": "Changes the renewal settings of a subscription",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.changeRenewalSettings",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "changeSeats": {
                    "description": "Changes the seats configuration of a subscription",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.changeSeats",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "delete": {
                    "description": "Cancels/Downgrades a subscription.",
                    "httpMethod": "DELETE",
                    "id": "reseller.subscriptions.delete",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "get": {
                    "description": "Gets a subscription of the customer.",
                    "httpMethod": "GET",
                    "id": "reseller.subscriptions.get",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates/Transfers a subscription for the customer.",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.insert",
                    "path": "customers/{customerId}/subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "list": {
                    "description": "Lists subscriptions of a reseller, optionally filtered by a customer name prefix.",
                    "httpMethod": "GET",
                    "id": "reseller.subscriptions.list",
                    "path": "subscriptions",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order",
                        "https://www.googleapis.com/auth/apps.order.readonly"
                    ]
                },
                "startPaidService": {
                    "description": "Starts paid service of a trial subscription",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.startPaidService",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                },
                "suspend": {
                    "description": "Suspends an active subscription",
                    "httpMethod": "POST",
                    "id": "reseller.subscriptions.suspend",
                    "path": "customers/{customerId}/subscriptions/{subscriptionId}/suspend",
                    "scopes": [
                        "https://www.googleapis.com/auth/apps.order"
                    ]
                }
            }
        }
    },
    "revision": "20151014",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "apps/reseller/v1sandbox/",
    "title": "Enterprise Apps Reseller API",
    "version": "v1sandbox"
}