{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive.readonly": {
                    "description": "View the files in your Google Drive"
                },
                "https://www.googleapis.com/auth/spreadsheets.readonly": {
                    "description": "View your Google Spreadsheets"
                },
                "https://www.googleapis.com/auth/drive": {
                    "description": "View and manage the files in your Google Drive"
                },
                "https://www.googleapis.com/auth/spreadsheets": {
                    "description": "View and manage your spreadsheets in Google Drive"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://sheets.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Sheets",
    "description": "Reads and writes Google Sheets.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/sheets/",
    "id": "sheets:v4",
    "kind": "discovery#restDescription",
    "name": "sheets",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "spreadsheets": {
            "methods": {
                "create": {
                    "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
                    "httpMethod": "POST",
                    "id": "sheets.spreadsheets.create",
                    "path": "v4/spreadsheets",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/spreadsheets"
                    ]
                },
                "get": {
                    "description": "Returns the spreadsheet at the given ID.\nThe caller must specify the spreadsheet ID.\n\nBy default, data within grids will not be returned.\nYou can include grid data one of two ways:\n\n* Specify a field mask listing your desired fields using the `fields` URL\nparameter in HTTP\n\n* Set the includeGridData\nURL parameter to true.  If a field mask is set, the `includeGridData`\nparameter is ignored\n\nFor large spreadsheets, it is recommended to retrieve only[...]",
                    "httpMethod": "GET",
                    "id": "sheets.spreadsheets.get",
                    "path": "v4/spreadsheets/{spreadsheetId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly",
                        "https://www.googleapis.com/auth/spreadsheets",
                        "https://www.googleapis.com/auth/spreadsheets.readonly"
                    ]
                },
                "batchUpdate": {
                    "description": "Applies one or more updates to the spreadsheet.\n\nEach request is validated before\nbeing applied. If any request is not valid then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how\nthey are applied. The replies will mirror the requests.  For example,\nif you applied 4 updates and the 3rd one had a reply, then the\nresponse will have 2 empty replies, the actual reply, and another [...]",
                    "httpMethod": "POST",
                    "id": "sheets.spreadsheets.batchUpdate",
                    "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/spreadsheets"
                    ]
                }
            },
            "resources": {
                "values": {
                    "methods": {
                        "update": {
                            "description": "Sets values in a range of a spreadsheet.\nThe caller must specify the spreadsheet ID, range, and\na valueInputOption.",
                            "httpMethod": "PUT",
                            "id": "sheets.spreadsheets.values.update",
                            "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        },
                        "get": {
                            "description": "Returns a range of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and a range.",
                            "httpMethod": "GET",
                            "id": "sheets.spreadsheets.values.get",
                            "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.readonly",
                                "https://www.googleapis.com/auth/spreadsheets",
                                "https://www.googleapis.com/auth/spreadsheets.readonly"
                            ]
                        },
                        "batchGet": {
                            "description": "Returns one or more ranges of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and one or more ranges.",
                            "httpMethod": "GET",
                            "id": "sheets.spreadsheets.values.batchGet",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/drive.readonly",
                                "https://www.googleapis.com/auth/spreadsheets",
                                "https://www.googleapis.com/auth/spreadsheets.readonly"
                            ]
                        },
                        "batchUpdate": {
                            "description": "Sets values in one or more ranges of a spreadsheet.\nThe caller must specify the spreadsheet ID,\na valueInputOption, and one or more\nValueRanges.",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.values.batchUpdate",
                            "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        }
                    }
                },
                "sheets": {
                    "methods": {
                        "copyTo": {
                            "description": "Copies a single sheet from a spreadsheet to another spreadsheet.\nReturns the properties of the newly created sheet.",
                            "httpMethod": "POST",
                            "id": "sheets.spreadsheets.sheets.copyTo",
                            "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
                            "scopes": [
                                "https://www.googleapis.com/auth/drive",
                                "https://www.googleapis.com/auth/spreadsheets"
                            ]
                        }
                    }
                }
            }
        }
    },
    "revision": "20160708",
    "rootUrl": "https://sheets.googleapis.com/",
    "servicePath": "",
    "title": "Google Sheets API",
    "version": "v4"
}