{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/tagmanager.delete.containers": {
                    "description": "Delete your Google Tag Manager containers"
                },
                "https://www.googleapis.com/auth/tagmanager.edit.containers": {
                    "description": "Manage your Google Tag Manager containers"
                },
                "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
                    "description": "Manage your Google Tag Manager container versions"
                },
                "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
                    "description": "Manage your Google Tag Manager accounts"
                },
                "https://www.googleapis.com/auth/tagmanager.manage.users": {
                    "description": "Manage user permissions of your Google Tag Manager data"
                },
                "https://www.googleapis.com/auth/tagmanager.publish": {
                    "description": "Publish your Google Tag Manager containers"
                },
                "https://www.googleapis.com/auth/tagmanager.readonly": {
                    "description": "View your Google Tag Manager containers"
                }
            }
        }
    },
    "basePath": "/tagmanager/v1/",
    "baseUrl": "https://www.googleapis.com/tagmanager/v1/",
    "batchPath": "batch",
    "canonicalName": "Tag Manager",
    "description": "API for accessing Tag Manager accounts and containers.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/tag-manager/api/v1/",
    "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/xcGgQKwhk2lzAuNnzm2cQsk-PZM\"",
    "id": "tagmanager:v1",
    "kind": "discovery#restDescription",
    "name": "tagmanager",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "accounts": {
            "methods": {
                "get": {
                    "description": "Gets a GTM Account.",
                    "httpMethod": "GET",
                    "id": "tagmanager.accounts.get",
                    "path": "accounts/{accountId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.manage.accounts",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                    ]
                },
                "list": {
                    "description": "Lists all GTM Accounts that a user has access to.",
                    "httpMethod": "GET",
                    "id": "tagmanager.accounts.list",
                    "path": "accounts",
                    "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.manage.accounts",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                    ]
                },
                "update": {
                    "description": "Updates a GTM Account.",
                    "httpMethod": "PUT",
                    "id": "tagmanager.accounts.update",
                    "path": "accounts/{accountId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.manage.accounts"
                    ]
                }
            },
            "resources": {
                "containers": {
                    "methods": {
                        "create": {
                            "description": "Creates a Container.",
                            "httpMethod": "POST",
                            "id": "tagmanager.accounts.containers.create",
                            "path": "accounts/{accountId}/containers",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                            ]
                        },
                        "delete": {
                            "description": "Deletes a Container.",
                            "httpMethod": "DELETE",
                            "id": "tagmanager.accounts.containers.delete",
                            "path": "accounts/{accountId}/containers/{containerId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.delete.containers"
                            ]
                        },
                        "get": {
                            "description": "Gets a Container.",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.containers.get",
                            "path": "accounts/{accountId}/containers/{containerId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                "https://www.googleapis.com/auth/tagmanager.readonly"
                            ]
                        },
                        "list": {
                            "description": "Lists all Containers that belongs to a GTM Account.",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.containers.list",
                            "path": "accounts/{accountId}/containers",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                "https://www.googleapis.com/auth/tagmanager.readonly"
                            ]
                        },
                        "update": {
                            "description": "Updates a Container.",
                            "httpMethod": "PUT",
                            "id": "tagmanager.accounts.containers.update",
                            "path": "accounts/{accountId}/containers/{containerId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.edit.containers"
                            ]
                        }
                    },
                    "resources": {
                        "macros": {
                            "methods": {
                                "create": {
                                    "description": "Creates a GTM Macro.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.macros.create",
                                    "path": "accounts/{accountId}/containers/{containerId}/macros",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "delete": {
                                    "description": "Deletes a GTM Macro.",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.macros.delete",
                                    "path": "accounts/{accountId}/containers/{containerId}/macros/{macroId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "get": {
                                    "description": "Gets a GTM Macro.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.macros.get",
                                    "path": "accounts/{accountId}/containers/{containerId}/macros/{macroId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "description": "Lists all GTM Macros of a Container.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.macros.list",
                                    "path": "accounts/{accountId}/containers/{containerId}/macros",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "update": {
                                    "description": "Updates a GTM Macro.",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.macros.update",
                                    "path": "accounts/{accountId}/containers/{containerId}/macros/{macroId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            }
                        },
                        "rules": {
                            "methods": {
                                "create": {
                                    "description": "Creates a GTM Rule.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.rules.create",
                                    "path": "accounts/{accountId}/containers/{containerId}/rules",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "delete": {
                                    "description": "Deletes a GTM Rule.",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.rules.delete",
                                    "path": "accounts/{accountId}/containers/{containerId}/rules/{ruleId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "get": {
                                    "description": "Gets a GTM Rule.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.rules.get",
                                    "path": "accounts/{accountId}/containers/{containerId}/rules/{ruleId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "description": "Lists all GTM Rules of a Container.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.rules.list",
                                    "path": "accounts/{accountId}/containers/{containerId}/rules",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "update": {
                                    "description": "Updates a GTM Rule.",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.rules.update",
                                    "path": "accounts/{accountId}/containers/{containerId}/rules/{ruleId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            }
                        },
                        "tags": {
                            "methods": {
                                "create": {
                                    "description": "Creates a GTM Tag.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.tags.create",
                                    "path": "accounts/{accountId}/containers/{containerId}/tags",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "delete": {
                                    "description": "Deletes a GTM Tag.",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.tags.delete",
                                    "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "get": {
                                    "description": "Gets a GTM Tag.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.tags.get",
                                    "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "description": "Lists all GTM Tags of a Container.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.tags.list",
                                    "path": "accounts/{accountId}/containers/{containerId}/tags",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "update": {
                                    "description": "Updates a GTM Tag.",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.tags.update",
                                    "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            }
                        },
                        "triggers": {
                            "methods": {
                                "create": {
                                    "description": "Creates a GTM Trigger.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.triggers.create",
                                    "path": "accounts/{accountId}/containers/{containerId}/triggers",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "delete": {
                                    "description": "Deletes a GTM Trigger.",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.triggers.delete",
                                    "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "get": {
                                    "description": "Gets a GTM Trigger.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.triggers.get",
                                    "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "description": "Lists all GTM Triggers of a Container.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.triggers.list",
                                    "path": "accounts/{accountId}/containers/{containerId}/triggers",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "update": {
                                    "description": "Updates a GTM Trigger.",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.triggers.update",
                                    "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            }
                        },
                        "variables": {
                            "methods": {
                                "create": {
                                    "description": "Creates a GTM Variable.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.variables.create",
                                    "path": "accounts/{accountId}/containers/{containerId}/variables",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "delete": {
                                    "description": "Deletes a GTM Variable.",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.variables.delete",
                                    "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "get": {
                                    "description": "Gets a GTM Variable.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.variables.get",
                                    "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "description": "Lists all GTM Variables of a Container.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.variables.list",
                                    "path": "accounts/{accountId}/containers/{containerId}/variables",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "update": {
                                    "description": "Updates a GTM Variable.",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.variables.update",
                                    "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                }
                            }
                        },
                        "versions": {
                            "methods": {
                                "create": {
                                    "description": "Creates a Container Version.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.create",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "delete": {
                                    "description": "Deletes a Container Version.",
                                    "httpMethod": "DELETE",
                                    "id": "tagmanager.accounts.containers.versions.delete",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "get": {
                                    "description": "Gets a Container Version.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.versions.get",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "list": {
                                    "description": "Lists all Container Versions of a GTM Container.",
                                    "httpMethod": "GET",
                                    "id": "tagmanager.accounts.containers.versions.list",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                                        "https://www.googleapis.com/auth/tagmanager.readonly"
                                    ]
                                },
                                "publish": {
                                    "description": "Publishes a Container Version.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.publish",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.publish"
                                    ]
                                },
                                "restore": {
                                    "description": "Restores a Container Version. This will overwrite the container's current configuration (including its macros, rules and tags). The operation will not have any effect on the version that is being served (i.e. the published version).",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.restore",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                                    ]
                                },
                                "undelete": {
                                    "description": "Undeletes a Container Version.",
                                    "httpMethod": "POST",
                                    "id": "tagmanager.accounts.containers.versions.undelete",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                },
                                "update": {
                                    "description": "Updates a Container Version.",
                                    "httpMethod": "PUT",
                                    "id": "tagmanager.accounts.containers.versions.update",
                                    "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                                    ]
                                }
                            }
                        }
                    }
                },
                "permissions": {
                    "methods": {
                        "create": {
                            "description": "Creates a user's Account & Container Permissions.",
                            "httpMethod": "POST",
                            "id": "tagmanager.accounts.permissions.create",
                            "path": "accounts/{accountId}/permissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "delete": {
                            "description": "Removes a user from the account, revoking access to it and all of its containers.",
                            "httpMethod": "DELETE",
                            "id": "tagmanager.accounts.permissions.delete",
                            "path": "accounts/{accountId}/permissions/{permissionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "get": {
                            "description": "Gets a user's Account & Container Permissions.",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.permissions.get",
                            "path": "accounts/{accountId}/permissions/{permissionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "list": {
                            "description": "List all users that have access to the account along with Account and Container Permissions granted to each of them.",
                            "httpMethod": "GET",
                            "id": "tagmanager.accounts.permissions.list",
                            "path": "accounts/{accountId}/permissions",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        },
                        "update": {
                            "description": "Updates a user's Account & Container Permissions.",
                            "httpMethod": "PUT",
                            "id": "tagmanager.accounts.permissions.update",
                            "path": "accounts/{accountId}/permissions/{permissionId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/tagmanager.manage.users"
                            ]
                        }
                    }
                }
            }
        }
    },
    "revision": "20141112",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "tagmanager/v1/",
    "title": "Tag Manager API",
    "version": "v1"
}