{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/ediscovery.readonly": {
                    "description": "View your eDiscovery data"
                },
                "https://www.googleapis.com/auth/ediscovery": {
                    "description": "Manage your eDiscovery data"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://vault.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Vault",
    "description": "Archiving and eDiscovery for G Suite.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/vault",
    "id": "vault:v1",
    "kind": "discovery#restDescription",
    "name": "vault",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "matters": {
            "methods": {
                "close": {
                    "description": "Closes the specified matter. Returns matter with updated state.",
                    "httpMethod": "POST",
                    "id": "vault.matters.close",
                    "path": "v1/matters/{matterId}:close",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "undelete": {
                    "description": "Undeletes the specified matter. Returns matter with updated state.",
                    "httpMethod": "POST",
                    "id": "vault.matters.undelete",
                    "path": "v1/matters/{matterId}:undelete",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "get": {
                    "description": "Gets the specified matter.",
                    "httpMethod": "GET",
                    "id": "vault.matters.get",
                    "path": "v1/matters/{matterId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery",
                        "https://www.googleapis.com/auth/ediscovery.readonly"
                    ]
                },
                "update": {
                    "description": "Updates the specified matter.\nThis updates only the name and description of the matter, identified by\nmatter id. Changes to any other fields are ignored.\nReturns the default view of the matter.",
                    "httpMethod": "PUT",
                    "id": "vault.matters.update",
                    "path": "v1/matters/{matterId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "delete": {
                    "description": "Deletes the specified matter. Returns matter with updated state.",
                    "httpMethod": "DELETE",
                    "id": "vault.matters.delete",
                    "path": "v1/matters/{matterId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "addPermissions": {
                    "description": "Adds an account as a matter collaborator.",
                    "httpMethod": "POST",
                    "id": "vault.matters.addPermissions",
                    "path": "v1/matters/{matterId}:addPermissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "list": {
                    "description": "Lists matters the user has access to.",
                    "httpMethod": "GET",
                    "id": "vault.matters.list",
                    "path": "v1/matters",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery",
                        "https://www.googleapis.com/auth/ediscovery.readonly"
                    ]
                },
                "create": {
                    "description": "Creates a new matter with the given name and description. The initial state\nis open, and the owner is the method caller. Returns the created matter\nwith default view.",
                    "httpMethod": "POST",
                    "id": "vault.matters.create",
                    "path": "v1/matters",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "reopen": {
                    "description": "Reopens the specified matter. Returns matter with updated state.",
                    "httpMethod": "POST",
                    "id": "vault.matters.reopen",
                    "path": "v1/matters/{matterId}:reopen",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "removePermissions": {
                    "description": "Removes an account as a matter collaborator.",
                    "httpMethod": "POST",
                    "id": "vault.matters.removePermissions",
                    "path": "v1/matters/{matterId}:removePermissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                }
            },
            "resources": {
                "holds": {
                    "methods": {
                        "get": {
                            "description": "Gets a hold by ID.",
                            "httpMethod": "GET",
                            "id": "vault.matters.holds.get",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        },
                        "list": {
                            "description": "Lists holds within a matter. An empty page token in ListHoldsResponse\ndenotes no more holds to list.",
                            "httpMethod": "GET",
                            "id": "vault.matters.holds.list",
                            "path": "v1/matters/{matterId}/holds",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ]
                        },
                        "update": {
                            "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts\nto a hold that covers an OU, nor can you add OUs to a hold that covers\nindividual accounts. Accounts listed in the hold will be ignored.",
                            "httpMethod": "PUT",
                            "id": "vault.matters.holds.update",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "create": {
                            "description": "Creates a hold in the given matter.",
                            "httpMethod": "POST",
                            "id": "vault.matters.holds.create",
                            "path": "v1/matters/{matterId}/holds",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "delete": {
                            "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
                            "httpMethod": "DELETE",
                            "id": "vault.matters.holds.delete",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        }
                    },
                    "resources": {
                        "accounts": {
                            "methods": {
                                "create": {
                                    "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that\nhas no held_org_unit set. Attempting to add an account to an OU-based\nhold will result in an error.",
                                    "httpMethod": "POST",
                                    "id": "vault.matters.holds.accounts.create",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery"
                                    ]
                                },
                                "delete": {
                                    "description": "Removes a HeldAccount from a hold. If this request leaves the hold with\nno held accounts, the hold will not apply to any accounts.",
                                    "httpMethod": "DELETE",
                                    "id": "vault.matters.holds.accounts.delete",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery"
                                    ]
                                },
                                "list": {
                                    "description": "Lists HeldAccounts for a hold. This will only list individually specified\nheld accounts. If the hold is on an OU, then use\n<a href=\"https://developers.google.com/admin-sdk/\">Admin SDK</a>\nto enumerate its members.",
                                    "httpMethod": "GET",
                                    "id": "vault.matters.holds.accounts.list",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery",
                                        "https://www.googleapis.com/auth/ediscovery.readonly"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "revision": "20180426",
    "rootUrl": "https://vault.googleapis.com/",
    "servicePath": "",
    "title": "G Suite Vault API",
    "version": "v1"
}