{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/webmasters": {
                    "description": "View and modify Webmaster Tools data for your verified sites"
                },
                "https://www.googleapis.com/auth/webmasters.readonly": {
                    "description": "View Webmaster Tools data for your verified sites"
                }
            }
        }
    },
    "basePath": "/webmasters/v3/",
    "baseUrl": "https://www.googleapis.com/webmasters/v3/",
    "batchPath": "batch",
    "description": "Lets you view Google Webmaster Tools data for your verified sites.",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/webmaster-tools/v3/welcome",
    "etag": "\"uUWyYHXmEn-ab7WLvo8qNz2S8ws/sCAxuVQJb4ynjZxsnsm28T2muEw\"",
    "id": "webmasters:v3",
    "kind": "discovery#restDescription",
    "name": "webmasters",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "sitemaps": {
            "methods": {
                "delete": {
                    "description": "Deletes a sitemap from this site.",
                    "httpMethod": "DELETE",
                    "id": "webmasters.sitemaps.delete",
                    "path": "sites/{siteUrl}/sitemaps/{feedpath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                },
                "get": {
                    "description": "Retrieves information about a specific sitemap.",
                    "httpMethod": "GET",
                    "id": "webmasters.sitemaps.get",
                    "path": "sites/{siteUrl}/sitemaps/{feedpath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "list": {
                    "description": "Lists sitemaps uploaded to the site.",
                    "httpMethod": "GET",
                    "id": "webmasters.sitemaps.list",
                    "path": "sites/{siteUrl}/sitemaps",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "submit": {
                    "description": "Submits a sitemap for a site.",
                    "httpMethod": "PUT",
                    "id": "webmasters.sitemaps.submit",
                    "path": "sites/{siteUrl}/sitemaps/{feedpath}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                }
            }
        },
        "sites": {
            "methods": {
                "add": {
                    "description": "Adds a site to the set of the user's sites in Webmaster Tools.",
                    "httpMethod": "PUT",
                    "id": "webmasters.sites.add",
                    "path": "sites/{siteUrl}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                },
                "delete": {
                    "description": "Removes a site from the set of the user's Webmaster Tools sites.",
                    "httpMethod": "DELETE",
                    "id": "webmasters.sites.delete",
                    "path": "sites/{siteUrl}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                },
                "get": {
                    "description": "Retrieves information about specific site.",
                    "httpMethod": "GET",
                    "id": "webmasters.sites.get",
                    "path": "sites/{siteUrl}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "list": {
                    "description": "Lists your Webmaster Tools sites.",
                    "httpMethod": "GET",
                    "id": "webmasters.sites.list",
                    "path": "sites",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                }
            }
        },
        "urlcrawlerrorscounts": {
            "methods": {
                "query": {
                    "description": "Retrieves a time series of the number of URL crawl errors per error category and platform.",
                    "httpMethod": "GET",
                    "id": "webmasters.urlcrawlerrorscounts.query",
                    "path": "sites/{siteUrl}/urlCrawlErrorsCounts/query",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                }
            }
        },
        "urlcrawlerrorssamples": {
            "methods": {
                "get": {
                    "description": "Retrieves details about crawl errors for a site's sample URL.",
                    "httpMethod": "GET",
                    "id": "webmasters.urlcrawlerrorssamples.get",
                    "path": "sites/{siteUrl}/urlCrawlErrorsSamples/{url}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "list": {
                    "description": "Lists a site's sample URLs for the specified crawl error category and platform.",
                    "httpMethod": "GET",
                    "id": "webmasters.urlcrawlerrorssamples.list",
                    "path": "sites/{siteUrl}/urlCrawlErrorsSamples",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters",
                        "https://www.googleapis.com/auth/webmasters.readonly"
                    ]
                },
                "markAsFixed": {
                    "description": "Marks the provided site's sample URL as fixed, and removes it from the samples list.",
                    "httpMethod": "DELETE",
                    "id": "webmasters.urlcrawlerrorssamples.markAsFixed",
                    "path": "sites/{siteUrl}/urlCrawlErrorsSamples/{url}",
                    "scopes": [
                        "https://www.googleapis.com/auth/webmasters"
                    ]
                }
            }
        }
    },
    "revision": "20140908",
    "rootUrl": "https://www.googleapis.com/",
    "servicePath": "webmasters/v3/",
    "title": "Webmaster Tools API",
    "version": "v3"
}