# See https://pub.dev/packages/mono_repo
dart:
- beta
- dev

stages:
- analyze_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
- unittest:
  - test: -p vm
  - test: -p chrome
