name: markdown_link_check
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/link_check_config.json'
